(function(){var d=window,f=document,h=parseInt,l="items",m="split",q="push",r="length",u="prototype",v,w=this,x=function(a,c,b){a=a[m](".");b=b||w;a[0]in b||!b.execScript||b.execScript("var "+a[0]);for(var e;a[r]&&(e=a.shift());)a[r]||void 0===c?b=b[e]?b[e]:b[e]={}:b[e]=c},y=Date.now||function(){return+new Date};var z=function(a){this.D=a},B=/\s*;\s*/;v=z[u];v.isEnabled=function(){return navigator.cookieEnabled};v.aa=function(a){return!/[;=\s]/.test(a)};v.ba=function(a){return!/[;\r\n]/.test(a)};
v.set=function(a,c,b,e,g,k){if(!this.aa(a))throw Error('Invalid cookie name "'+a+'"');if(!this.ba(c))throw Error('Invalid cookie value "'+c+'"');void 0!==b||(b=-1);g=g?";domain="+g:"";e=e?";path="+e:"";k=k?";secure":"";b=0>b?"":0==b?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(y()+1E3*b)).toUTCString();this.ha(a+"="+c+g+e+b+k)};v.V=function(){return this.H().keys};v.Y=function(){return this.H().values};v.ha=function(a){this.D.cookie=a};
v.W=function(){return(this.D.cookie||"")[m](B)};v.H=function(){for(var a=this.W(),c=[],b=[],e,g,k=0;g=a[k];k++)e=g.indexOf("="),-1==e?(c[q](""),b[q](g)):(c[q](g.substring(0,e)),b[q](g.substring(e+1)));return{keys:c,values:b}};var C={},D=function(a,c,b){this.b=a;this.J=c;this.C=b;this.u=Math.floor((new Date).getTime()/1E3);this.m=8035200;this.i=void 0};D[u].ka=function(){return this.b+"$"+this.J+":"+this.C};D[u].la=function(){var a=this.b+"$"+this.J+":"+this.u+":"+this.m;"string"==typeof this.i&&(a=a.concat(":",this.i));return a};D[u].ja=function(a,c,b){this.u=a;this.m=c;this.i=b};D[u].$=function(){return(new Date).getTime()>(new Date(1E3*(this.u+this.m))).getTime()};
var G=function(a){var c={},b=new z(f);if(!b.isEnabled())return c;var e=b.V(),b=b.Y();if(null==e||null==b)return c;for(var g=0;g<e[r];g++)if("__utmx"==e[g])for(var k=F(b[g],a),p=0;p<k[r];p++){var n=/([^$]+)\$([^:]+):(.*)/.exec(k[p]);null!==n&&4==n[r]&&(n=new D(n[1],n[2],n[3]),c[n.b]=n)}g={};for(k=0;k<e[r];k++)if("__utmxx"==e[k])for(p=F(b[k],a),n=0;n<p[r];n++){var t=/([^$]+)\$([^:]+):([^:]+):([^:]+):?(.*)/.exec(p[n]);if(null!==t&&5<=t[r]){var E=t[1],A=c[E];"undefined"!=typeof A&&(A.ja(h(t[3],10),h(t[4],
10),6==t[r]?t[5]:void 0),A.$()||(g[E]=A))}}return g},F=function(a,c){var b=a[m](".");return"string"==typeof c&&0<b[r]&&b[0]!=c?[]:b.slice(1)};var H=function(a,c,b,e,g){this.b=g||H.DEFAULT_ID;this.a=a;this.g=c;this.h=b;this.f=e;this.L=!1};H.experiments_={"qcVdWNyCQ3WU__e6nRcYyQ":{"api_version":"V1","method":"experiments.get","error":{"code":404,"message":"Experiment not available"}}};H.DEFAULT_ID="qcVdWNyCQ3WU__e6nRcYyQ";v=H[u];v.s=function(a){if(!this.l()&&!this.I()){var c=new z(f);if(I(c.isEnabled(),"Unable to write cookies")){var b=this.v(a),e=this.G(),g=G(e);g[this.b]=new D(this.b,"0",b);var b=e,k;for(k in g)var p=g[k],b=b.concat(".",p.ka()),e=e.concat(".",p.la());c.set("__utmx",b,this.f,this.g,this.j());c.set("__utmxx",e,this.f,this.g,this.j());-2!=a[0]&&this.M(a)}}};
v.M=function(a){d.gaData||(d.gaData={});d.gaData.expId=this.b;d.gaData.expVar=this.v(a)};v.j=function(){if("string"==typeof this.a&&""!=this.a&&"none"!=this.a&&"auto"!=this.a)return this.a;if("none"==this.a)return null;var a=""+f.domain;return 0==a.indexOf("www.")?a.substring(4):a};v.G=function(){if(!this.h)return"1";var a=this.j();if(a){var c=1,b=0,e;if(a)for(c=0,e=a[r]-1;0<=e;e--)b=a.charCodeAt(e),c=(c<<6&268435455)+b+(b<<14),b=c&266338304,c=0!=b?c^b>>21:c;a=String(c)}else a="1";return a};
v.v=function(a){for(var c=0;c<a[r];c++)if(-2==a[c])return"";return a.join("-")};v.o=function(a){if(0==a[r])return-2;a=a[m]("-");for(var c=[],b=0;b<a[r];b++)c[b]=h(a[b],10);return c};var I=function(a,c){!a&&c&&console&&console.error&&console.error(c);return a};v=H[u];v.l=function(){var a=d._gaUserPrefs;return a&&a.ioo&&a.ioo()};
v.K=function(){if(!this.L){var a=H.experiments_[this.b];this.L=!0;if(!I("object"==typeof a,"Could not load experiment")||a.error)return!1;this.c=a.data}return I("object"===typeof this.c,"Could not load experiment")};v.F=function(){if(this.l())return-2;var a=this.I();if(a)return a;a=G(this.G())[this.b];if(!a)return-1;a=this.o(a.C);-2!=a&&this.M(a);return a};
v.R=function(){if(this.l()||!this.K())return 0;var a=this.F();if(-2==a||this.Z(a))return 0;if(-1!==a)return a;if(!this.X())return this.s([-2]),0;a=this.ca();this.s(a);return a};v.X=function(a){return("number"==typeof a?a:Math.random())<this.c.participation};
v.ca=function(a){I("undefined"===typeof _gaq,"Variations should be chosen before hit is sent to GA");a="number"==typeof a?a:Math.random();for(var c=0;c<this.c[l][r];c++){var b=this.c[l][c];if(a<b.weight)return this.o(b.id);a-=b.weight}I(!1,"The combinations weights did not add up to 1");return[0]};v.U=function(a){return this.K()&&I(0<=a&&a<this.c[l][r])?this.c[l][a]:null};
v.I=function(){var a=/#utmxid=[-_a-zA-Z0-9]{22};utmxpreview=(\d{1,2});/.exec(d.location.hash);return a?(a=this.U(h(a[1],10)),this.o(a.id)):null};v.Z=function(a){if("number"===typeof a)return!1;a=this.v(a);for(var c=0;c<this.c[l][r];c++){var b=this.c[l][c];if(b.id==a)return b.disabled}I(!1,"Unable to locate combination with id "+a);return!0};C=C||{};C.P=0;x("cxApi.ORIGINAL_VARIATION",C.P,void 0);C.O=-1;x("cxApi.NO_CHOSEN_VARIATION",C.O,void 0);C.N=-2;x("cxApi.NOT_PARTICIPATING",C.N,void 0);C.A="auto";x("cxApi.DEFAULT_DOMAIN",C.A,void 0);C.B=48211200;x("cxApi.DEFAULT_EXPIRATION_SECONDS",C.B,void 0);C.w="/";x("cxApi.DEFAULT_COOKIE_PATH",C.w,void 0);C.a=C.A;C.g=C.w;C.h=!0;C.f=C.B;C.ea=function(a,c){I("string"==typeof c||"undefined"==typeof c,"Invalid experiment id: "+c)&&(new H(C.a,C.g,C.h,C.f,c)).s([a])};
x("cxApi.setChosenVariation",C.ea,void 0);C.ia=function(a){I("string"==typeof a,"Invalid domain name: "+a)&&(C.a=a)};x("cxApi.setDomainName",C.ia,void 0);C.ga=function(a){I("string"==typeof a,"Invalid cookie path: "+a)&&(C.g=a)};x("cxApi.setCookiePath",C.ga,void 0);C.da=function(a){I("boolean"==typeof a,"Invalid value for allowHash: "+typeof a)&&(C.h=a)};x("cxApi.setAllowHash",C.da,void 0);C.fa=function(a){I("number"==typeof a,"Invalid cookieExpirationSeconds: "+a)&&(C.f=a)};
x("cxApi.setCookieExpirationSeconds",C.fa,void 0);C.S=function(a){I("string"==typeof a||"undefined"==typeof a,"Invalid experiment id: "+a);a=(new H(C.a,C.g,C.h,C.f,a)).R();return"number"===typeof a?a:a[0]};x("cxApi.chooseVariation",C.S,void 0);C.T=function(a){I("string"==typeof a||"undefined"==typeof a,"Invalid experiment id: "+a);a=(new H(C.a,C.g,C.h,C.f,a)).F();return"number"===typeof a?a:a[0]};x("cxApi.getChosenVariation",C.T,void 0);})();
