(function(){var g=void 0,h=true,i=null,j=false,k,l=this;function aa(a,b){function c(){}c.prototype=b.prototype;a.T=b.prototype;a.prototype=new c;a.prototype.constructor=a};function ba(a,b){var c;c=new Image(1,1);if(b)c.onerror=b;c.src=a}function ca(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function da(a,b){var c="",d=ea(encodeURIComponent(a));d.splice(b||5,d.length);o(d,function(a){if(a==0)a="A";else{a>>>=0;for(var b="",d;a>0;)d=a%64,b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(d)+b,a>>>=6;a=b}c+=a});return c}
function ea(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,d=4023233417,e=2562383102,f=271733878,m=3285377520,q=[],n,z,x,K,L,V=Math.ceil((a.length/4+2)/16),S=[V],A=0,w;A<V;A++){S[A]=[];for(n=0;n<16;n++)S[A][n]=a.charCodeAt(A*64+n*4)<<24|a.charCodeAt(A*64+n*4+1)<<16|a.charCodeAt(A*64+n*4+2)<<8|a.charCodeAt(A*64+n*4+3)}A=(a.length-1)*8;a=V-1;S[a][14]=Math.floor(A/Math.pow(2,32));S[a][15]=A&4294967295;for(A=0;A<V;A++){for(w=0;w<16;w++)q[w]=S[A][w];
for(w=16;w<80;w++)q[w]=(q[w-3]^q[w-8]^q[w-14]^q[w-16])<<1|(q[w-3]^q[w-8]^q[w-14]^q[w-16])>>>31;a=c;n=d;z=e;x=f;K=m;for(w=0;w<80;w++)L=Math.floor(w/20),L=(a<<5|a>>>27)+(L==0?n&z^~n&x:L==1?n^z^x:L==2?n&z^n&x^z&x:n^z^x)+K+b[L]+q[w]&4294967295,K=x,x=z,z=n<<30|n>>>2,n=a,a=L;c=c+a&4294967295;d=d+n&4294967295;e=e+z&4294967295;f=f+x&4294967295;m=m+K&4294967295}return[c,d,e,f,m]}
function fa(a){var b=l.navigator,c=l.window.screen,d=[b.userAgent,b.platform,(new Date).getTimezoneOffset(),c.width+c.height+c.colorDepth];o(b.plugins,function(a){d.push(a.name+a.description+a.filename+a[0].type)});b=l.performance;d=d.concat([b&&b.now?b.now():"",document.title,l.location.href,p(),ca()]);return d.concat(a||[]).join()}function r(a,b,c){var d=Array.prototype.slice,e=d.call(arguments,2);return function(){return a.apply(b,e.concat(d.call(arguments)))}}
function s(a){return typeof a!=="undefined"}function t(a){return a.replace(/^www\./,"")}function u(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)}function ga(a,b){var c=l;c.removeEventListener?c.removeEventListener(a,b,j):c.detachEvent&&c.detachEvent("on"+a,b)}function v(a){return typeof a==="number"}function y(a){return typeof a==="string"}function ha(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}
function p(){return(new Date).getTime()}function ia(a){return encodeURIComponent(a)}function B(a){return!!a&&a.constructor===Object}function ja(a,b){if(!B(a)||!B(b))return a===b;var c=0,d=h;o(a,function(a,e){c++;return d=a===b[e]});if(!d)return j;var e=0;o(b,function(){e++});return c===e}function o(a,b){if(B(a)===h)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===j)break}else{c=0;for(var d=a.length;c<d;c++)if(b(a[c],c)===j)break}}
function ka(a,b){for(var c=0,d=a.length;c<d;c++)if(b(a[c]))return c;return-1}function la(a){if(B(a)===j)return"";var b=[];o(a,function(a,d){b.push(encodeURIComponent(d)+"::"+encodeURIComponent(a))});return b.join("&")}function ma(a){B(a)===h&&(a="");var b={};o(a.split("&"),function(a){a=a.split("::");a.length===2&&(b[decodeURIComponent(a[0])]=decodeURIComponent(a[1]))});return b}
function na(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],d=0,e=b.length;d<=e;d++)c[d]=[d];for(var f=0,m=a.length;f<=m;f++)c[0][f]=f;for(var q,n,z,d=1;d<=e;d++)for(f=1;f<=m;f++)q=d-1,n=f-1,z=c[q][n],b.charAt(q)==a.charAt(n)?c[d][f]=z:(n=c[d][n]+1,q=c[q][f]+1,z+=2,c[d][f]=Math.min(n,q,z));return c[b.length][a.length]}var oa;function pa(){}var qa=l.setInterval,C=l.clearInterval,ra=l.setTimeout,D=l.clearTimeout;
function sa(a,b){var c={};o(b,function(b,e){c[b]=r(a[e],a)});return c};function ta(a,b,c){b=b||"*";c=c||document;if("querySelectorAll"in c)return c.querySelectorAll(b+"["+a+"]");for(var d=[],b=c.getElementsByTagName(b),c=b.length;c--;)b[c].getAttribute(a)&&d.push(b[c]);return d}function E(a,b){var c=i;b&&(c=b.getAttribute(a));if(c===i){var d=ta(a,"*",b);d.length!==0&&(c=d[0].getAttribute(a))}return c}function ua(a,b,c){return a===g?j:c===g&&a.getAttribute(b)||a.getAttribute(b)===c?a:a===document.body?j:ua(a.parentNode,b,c)}
function va(a,b,c){a="page"+a+"Offset";b="scroll"+b;if(c&&(c=ta("data-cb-scroll-element"))&&c.length)return c[0][b];if(v(l[a]))return l[a];else if(document.body&&document.body[b])return document.body[b];else if(document.documentElement[b])return document.documentElement[b];return 0}function wa(a){var b=document,b=b[b.compatMode==="CSS1Compat"?"documentElement":"body"]["client"+a]||0;window["inner"+a]&&(b=Math.min(window["inner"+a],b));return b}
function F(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0}function xa(a,b,c){var d=a.ownerDocument.documentElement,e=0,f=s(c)?c+1:-1;y(b)?(b=b.toLowerCase(),c=function(a){return(a=a.nodeName)&&a.toLowerCase()===b}):c=b;for(;a&&a!==d&&e!==f;){if(c(a))return a;a=a.parentNode;e++}return i}function ya(a){return a.nodeName&&a.nodeName.toLowerCase()==="a"&&(!a.namespaceURI||a.namespaceURI==="http://www.w3.org/1999/xhtml")}
function za(a){a=a||window.event;return!a?i:xa(a.target||a.srcElement,ya,10)}function Aa(a,b){var c=document.createElement(a);o(b,function(a,b){c.setAttribute(b,a)});return c}function Ba(a){var b=s(g)?g:{};b.src=a;a=Aa("script",b);a.setAttribute("type","text/javascript");b=document.head||document.getElementsByTagName("head")[0];s(g)?g.appendChild(a):b&&b.appendChild(a)}
function Ca(){if(s(Da))return Da;var a;a:{a=Ea;for(var b=document.getElementsByTagName("script"),c=b.length-1;c>-1;c--)if(a.test(b[c].getAttribute("src"))){a=b[c];break a}a=g}return Da=s(a)}var Da;function Fa(){this.P={};this.nb=1}k=Fa.prototype;k.G=function(a,b,c){this.nb++;this.P[a]=this.P[a]||{};this.P[a][this.nb]=[b,c];return this.nb};k.Q=function(a){if(y(a))this.P[a]=g,delete this.P[a];else if(v(a)){var b=h;o(this.P,function(c){o(c,function(d,e){if(parseInt(e,10)===a)return c[e]=g,delete c[e],b=j});return b})}};k.O=function(a,b){if(this.P[a]){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];o(this.P[a],function(a){var b;a&&a.length===2&&(b=a[0],a=a[1],b.apply(a,c))})}};
k.addEventListener=function(a,b){var c=this.G(a,b);b._cbEventId=c};k.removeEventListener=function(a,b){this.P[a]&&this.P[a][b._cbEventId]&&this.P[a][b._cbEventId][0]===b&&this.Q(b._cbEventId)};var G=new Fa,Ga="o",Ha={G:Ga,Q:"f"},Ia="a";var H={};
H.q=function(){H.bb?H.Ha("pageload"):(H.Rb=[{target:l,event:"scroll"},{target:document.body,event:"keydown"},{target:document.body,event:"mousemove"},{target:l,event:"resize"},{target:document.body,event:"mousedown"}],H.Oa=i,H.mb=j,H.ra=i,H.Db={},H.Qa={},o(H.Rb,function(a){var b=a.event;u(a.target,b,function(a){H.Ha.call(H,b,a)})}),G.G("f",function(){H.Ha("focus")}),H.Ha("pageload"),u(document.body,"click",function(a){(a=za(a))&&G.O("c",a)},h),u(document.body,"contextmenu",function(a){(a=za(a))&&
G.O("r",a)}),H.bb=h)};H.Ub=function(){var a,b=H.Db.keydown;if(b===g)return j;b=p()-b;return b<=(a||15E3)&&b>=0};H.oa=function(a,b){var c=H.Qa[a];if(!c)return"";var b=b||p(),d,e=0;o(c,function(a){d=Math.floor((b-a)/1E3);d>=0&&d<16&&(e|=1<<d)});c=("0000"+e.toString(16)).slice(-4);return c=="0000"?"":c};H.yc=function(){H.Qa={}};H.sb=100;H.Ha=function(a,b){if(!b)b=window.event;if(b&&a==="keydown"){var c=b.keyCode?b.keyCode:b.which;if(c===32||c>36&&c<41)a="scroll"}H.Cc(a);H.Oa===i?H.Lb():H.mb=h};
H.Cc=function(a){var b=p();H.Db[a]=b;var c=H.Qa[a];c?c.length<2?c.push(b):c[c.length-2]>b-1E3?c[c.length-1]=b:c.push(b):c=[b];c.length>32&&c.shift();H.Qa[a]=c};H.Lb=function(){H.Oa=ra(H.Yb,H.sb);G.O(Ia);H.ra!==i&&D(H.ra);H.ra=ra(function(){G.O("i");D(H.ra);H.ra=i},5E3+H.sb)};H.Yb=function(){D(H.Oa);H.Oa=i;if(H.mb)H.mb=j,H.Lb()};var Ja=/[?&]__cb_debug=([^&]+)/i,Ea=/:\/\/static2\.chartbeat.com\/js\/chartbeat(_[a-z]+)?\.js$/;var Ka,La,Ma,Na,Oa;(function(){var a,b;o(["","moz","o","ms","webkit"],function(c){a=(c+"Hidden").charAt(0).toLowerCase()+(c+"Hidden").slice(1);if(typeof l.document[a]==="boolean")return b=c,j});b!==g&&(Na=a,Oa=(b+"VisibilityState").charAt(0).toLowerCase()+(b+"VisibilityState").slice(1),Ma=b+"visibilitychange")})();var I=j;function Pa(){I=Oa&&l.document[Oa]==="prerender"?h:j}function Qa(){La=h;G.O("f")}function Ra(){La=j;G.O("b")}
function Sa(a,b,c){l.addEventListener?l.addEventListener(a,c,j):l.document.attachEvent&&l.document.attachEvent(b,c)}function Ta(){var a=h;l.document.hasFocus&&(a=l.document.hasFocus());var b=j;Na&&(b=l.document[Na]);return a&&!b}function Ua(){Ta()?Qa():Ra()}function Va(a){Pa();if(I){var b=j,c=function(){b||(Pa(),I||(b=h,a(),l.window.setTimeout(function(){l.document.removeEventListener(Ma,c,j)},100)))};l.document.addEventListener(Ma,c,j)}else a()};function J(){this.k=l._sf_async_config||{};this.wb=r(this.Hb,this)}J.prototype.q=function(){this.Ja=0};J.prototype.Hb=function(){};J.prototype.va=function(a){I||ba(a,this.wb)};J.prototype.Z=function(){this.wb=i};function Wa(a){var b={};a&&(a.charAt(0)=="?"&&(a=a.substring(1)),a=a.replace("+"," "),o(a.split(/[&;]/g),function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])}));return b}function Xa(a,b){var c="",d=l.location.href.split("?");if(d.length){var d=Wa(d[1]),e=b||a;d[e]&&(c=d[e])}return c}function Ya(a,b){return!b?h:a==="http:"&&b==="80"||a==="https:"&&b==="443"}
function Za(a,b){var c=[];o(b,function(b){var e=a[b];s(e)&&(Object.prototype.toString.call(e)==="[object Array]"?o(e,function(a){c.push(b+"="+a)}):B(e)?o(e,function(a,b){c.push(b+"="+a)}):((e+"").length||b=="r")&&c.push(b+"="+e))});c.push("_");return c.join("&")}
function $a(a){var b={hostname:"",pathname:"",search:"",protocol:"",port:"",hash:""};if(!a)return b;var c=document.createElement("a"),d=l.location;if(!/^https?:/.test(a)&&a.indexOf("javascript:")!==0)if(a.indexOf("//")===0)a=d.protocol+a;else if(a.indexOf("/")===0)var e=Ya(d.protocol,d.port)?"":d.port,a=d.protocol+"//"+d.hostname+(e?":"+e:"")+a;else{var e=document.baseURI||d.href,f=e.indexOf("?");f===-1&&(f=e.indexOf("#"));if(f===-1)f=e.length;f=e.lastIndexOf("/",f);a=f===-1?"/"+a:e.substr(0,f)+"/"+
a}c.href=a;b.hostname=c.hostname;b.pathname=c.pathname;b.search=c.search;b.protocol=c.protocol;b.port=c.port;b.hash=c.hash;if(b.pathname.charAt(0)!=="/")b.pathname="/"+b.pathname;if(b.hostname==="")b.hostname=d.hostname;if(b.protocol==="")b.protocol=d.protocol;if(b.protocol==="javascript:")b.pathname="",b.hostname="",b.port="",b.hash="";if(Ya(b.protocol,b.port)||b.port==="0")b.port="";return b}
function ab(a){var b=a.protocol;a.hostname&&(b+="//"+a.hostname,a.port&&(b+=":"+a.port));return b+a.pathname+a.search+a.hash};function M(a,b,c){a[b]=a[b]||c}function bb(a,b){for(var c=l[a]||[];c.length;)b(c.shift());l[a]={push:b}}function cb(a){o(document.getElementsByTagName("script"),function(b){if(b.src.match(/chartbeat.js/))return b=Wa(b.src.split("?")[1]),M(a,"uid",b.uid),M(a,"domain",b.domain),j})}function db(a,b){return a[b]?encodeURIComponent(a[b]):""}function eb(a){var b={};o(a,function(a,d){d.charAt(0)=="_"&&(b[d]=a)});return b};function N(a){var b=a===document.documentElement?a.scrollHeight:a.offsetHeight,c=a.offsetWidth;if(b<=1||c<=1){var d=fb(a,["overflow","overflow-x","overflow-y"]);d.overflow==="hidden"||d["overflow-x"]==="hidden"||d["overflow-y"]==="hidden"||o(a.getElementsByTagName("iframe"),function(a){var d=a.offsetHeight,a=a.offsetWidth;if(d>1&&a>1)return b=d,c=a,j})}return{height:b,width:c}}function gb(a){a=N(a);return a.height*a.width}
function hb(a){var b;"contains"in document.documentElement&&!document.documentElement.contains(a)?b=j:(b=N(a),b=b.height>1&&b.width>1);if(!b)return j;b=fb(a,["visibility","display","overflow","opacity"]);if(b.visibility=="hidden"||b.display=="none"||b.opacity=="0")return j;if(b.overflow=="hidden"&&(a.offsetHeight==0||a.offsetWidth==0))return j;b=h;for(var c=a.parentElement;c&&b;){var d;if(c.scrollHeight===c.clientHeight&&c.scrollWidth===c.clientWidth)d=j;else{var e=fb(c,["overflow","overflow-x","overflow-y"]);
d=e.overflow;var f=e["overflow-x"],e=e["overflow-y"];d=d==="auto"||d==="scroll"||f==="auto"||f==="scroll"||e==="auto"||e==="scroll"}d&&(b=ib(a,c));c=c.parentElement}return b&&ib(a,i)}function ib(a,b){var c,d;if(b){var e=N(b);c=e.width;d=e.height}else c=wa("Width"),d=wa("Height");var f=N(a),e=f.height,f=f.width,m=jb(a,b),q=m.y,m=m.x;c=Math.min(m+f,f,c,c-m);d=Math.min(q+e,e,d,d-q);if(c<0||d<0)return j;e*=f;return c*d>=(e>=242500?0.3:0.5)*e}
function jb(a,b,c){var d=a.offsetLeft,e=a.offsetTop,f=kb(a);d+=f.x;e+=f.y;for(var m=j,q=c?0:va("X","Left",g),n=c?0:va("Y","Top",g),f=a.offsetParent;a&&a!==b&&a!==document.body;){if(a===f)f=kb(a),d+=a.offsetLeft+f.x,e+=a.offsetTop+f.y,f=a.offsetParent;c||(d-=a.scrollLeft,e-=a.scrollTop);if(fb(a,["position"]).position==="fixed"){m=h;break}a=a.parentElement}c||(d-=b?b.scrollLeft:q,e-=b?b.scrollTop:n);m&&(d+=q,e+=n);return{x:d,y:e}}
function fb(a,b){var c={},d,e;l.getComputedStyle?d=l.getComputedStyle(a,i):a.currentStyle?e="currentStyle":a.style&&(e="style");o(b,function(b){c[b]=d?d[b]||d.getPropertyValue(b):a[e][b]});return c}var lb=/matrix(3d)?\((.*)\)/;function kb(a){var b={x:0,y:0},a=fb(a,["transform"]).transform;if(!y(a))return b;var c=a.match(lb);if(!c)return b;var a=c[2].split(", "),d;s(c[1])?(c=12,d=13):(c=4,d=5);b.x=parseInt(a[c],10);b.y=parseInt(a[d],10);return b};var O={},mb={Ya:"g"};O.ub={IDLE:0,Jc:1,Ic:2,tb:3};O.S=0;O.q=function(){if(!O.bb)G.G(Ia,O.fc,O),G.G("i",O.ic,O),G.G("f",O.hc,O),G.G("b",O.gc,O),O.bb=h};O.Ya=function(){return O.S};O.fc=function(){O.S===1?O.ea(3):O.S===0&&O.ea(2)};O.ic=function(){O.S===3?O.ea(1):O.S===2&&O.ea(0)};O.hc=function(){(O.S===0||O.S===2)&&O.ea(3)};O.gc=function(){O.S===3?O.ea(2):O.S===1&&O.ea(0)};O.ea=function(a){O.S=a;G.O("s",a)};function nb(a,b){this.Za=a||g;this.ua=b||g;this.ka=this.U=0;this.ab=r(this.ab,this)}k=nb.prototype;k.q=function(){this.ka=this.U=0;this.xa=i;this.zc=G.G("s",this.pa,this);this.pa(O.Ya())};k.pa=function(a){C(this.xa);this.xa=i;if(a===O.ub.tb)this.xa=qa(this.ab,1E3)};k.ab=function(){if(this.Za===g||this.Za())this.U++,this.ka++,this.ua&&this.ua()};k.terminate=function(){C(this.xa);this.xa=i;G.Q(this.zc)};k.Z=function(){this.terminate();this.ua=this.Za=g};function P(a,b){J.call(this);this.J=a;this.uc=b;this.aa=a.getAttribute("data-cb-ad-id")||a.id||"";this.ob=r(this.ob,this);this.vb=0;this.Ta=ob;var c=this;this.$=new nb(function(){pb(c);return hb(c.M)},r(this.ua,this));qb&&this.Ba();this.q()}var qb;aa(P,J);
P.prototype.q=function(){P.T.q.call(this);this.vb++;this.Jb=j;this.N={};this.N.campaignId="";this.N.creativeId="";this.N.placementId="";this.N.siteId="";this.N.server_height="";this.N.server_width="";this.N.lineId="";this.M=this.J;this.$a=this.fb=this.Xa=j;this.Wa={mc:j,frame:j};pb(this);this.Ua=rb;this.Qb=j;this.pb={};this.$.q();this.Pb=j;this.za=0;this.na=i;this.Fc=G.G("s",this.pa,this);this.pa(O.Ya())};
P.prototype.Ba=function(){var a=this;this.ga=new qb(this.aa,function(){return{adContainer:a.J,creativeContainer:a.M,viewableIntervals:a.za,creativeScenarios:a.Wa,adPingData:sb(a)}})};var ob=0,rb=0;P.prototype.pa=function(a){if(this.na!==i)C(this.na),this.na=i;this.za=0;if(a===O.ub.tb)this.na=qa(this.ob,100)};P.prototype.ob=function(){if(hb(this.M)){if(this.za++,this.za>=10)this.Pb=h,tb(this),G.O("p")}else this.za=0;this.ga&&this.ga.update()};function tb(a){G.Q(a.Fc);C(a.na);a.na=i}
P.prototype.ua=function(){G.O("e",this);this.Qb&&G.O("z",this.pb,1);this.ga&&this.ga.update()};var ub={300:{250:1,600:1,1050:1},180:{150:1},160:{600:1},728:{90:1},970:{90:1,66:1,250:1,415:1,550:1},120:{60:1},88:{31:1},62:{88:1},196:{31:1}};
function pb(a){var b=l._sf_async_config;if(b&&(b=b.creativeDetection,b===j||y(b)&&b!=="iab"))return;var c=gb(a.J);if(a.M!==a.J)if(b=gb(a.M),b>c)a.M=a.J;else if(b>0)return;o(["iframe","embed","object","img","div"],function(b){o(a.J.getElementsByTagName(b),function(b){var d=N(b);if(!(d.height*d.width>c)&&ub[d.width]&&ub[d.width][d.height])return a.M=b,a.Wa.mc=h,j});return a.M===a.J})}
function vb(a,b,c){if(b.exclude)a.Xa=h;if(b.noRefresh)a.fb=h;a.N=b;a.$a=!!c;if(a.$a){var d=h,e=l._sf_async_config;if(e&&(e=e.creativeDetection,e===j||y(e)&&e!=="iframe"))d=j;if(d&&gb(c)>0)a.M=c,a.Wa.frame=h}G.O("p");if(b=b.vizu)a.Qb=h,a.pb=ma(b),G.O("z",a.pb,a.$.U)}function Q(a,b){return a.N?a.N[b]:""}function wb(a){var b={};b.id=a.aa;b.engagedSeconds=a.$.U;b.campaignId=Q(a,"campaignId");b.creativeId=Q(a,"creativeId");return b}
function sb(a){var b={};b.at=a.Mc;b.an=a.aa;b.as=a.Ja;b.aj=a.Jb?0:240;b.aE=a.$.U;if(a.M){var c=jb(a.M,g,h);b.ax=c.x;b.ay=c.y;c=N(a.M);b.aw=c.width;b.ah=c.height}b.aV=a.Pb;b.ao=a.vb;b.ac=Q(a,"campaignId");b.av=Q(a,"creativeId");b.aP=Q(a,"placementId");b.aS=Q(a,"siteId");b.aW=Q(a,"server_width");b.aH=Q(a,"server_height");b.aL=Q(a,"lineId");b.exclude=a.Xa;b.am=a.Ta;b.aR=a.Ua;return b}
function xb(a){var b=encodeURIComponent(a.an),c=a.aE,d=a.ax,e=a.ay,f=a.aw,m=a.ah,q=encodeURIComponent(a.av||""),n=encodeURIComponent(a.ac||""),z=encodeURIComponent(a.aP||""),x=encodeURIComponent(a.aS||""),K=encodeURIComponent(a.aH||""),L=encodeURIComponent(a.aW||""),V=encodeURIComponent(a.aL||""),S=a.ao,A=a.aR,w=a.am,gc=a.aV?"1":"0";a.exclude&&(n="");return b+"="+[c,d,e,f,m,n,q,S+"."+A,gc,z,x,K,L,V,w].join("::")}
P.prototype.ya=function(){if(!this.$a){var a=this.J,b={};b.campaignId=E("data-cb-campaign-id",a)||"";b.creativeId=E("data-cb-creative-id",a)||"";b.placementId=E("data-cb-placement-id",a)||"";b.siteId=E("data-cb-site-id",a)||"";b.server_height=E("data-cb-creative-height",a)||"";b.server_width=E("data-cb-creative-width",a)||"";b.lineId=E("data-cb-line-id",a)||"";if(E("data-cb-exclude",a))this.Xa=h;if(E("data-cb-no-refresh",a))this.fb=h;ja(b,this.N)||vb(this,b)}};
P.prototype.refresh=function(){this.Jb=h;tb(this);this.$.terminate();this.q()};P.prototype.Z=function(){P.T.Z.call(this);tb(this);C(this.Lc);this.$.Z();this.uc=this.N=this.M=this.J=this.$=i;this.ga&&this.ga.dispose()};var R={};R.Xb=function(){try{R.create("_cb_test","1",1);var a=R.B("_cb_test");R.remove("_cb_test");return a==="1"}catch(b){return j}};R.B=function(a){a+="=";var b="";o(document.cookie.split(";"),function(c){for(;c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return b=c.substring(a.length,c.length),j});return b};
R.create=function(a,b,c){var d=l._sf_async_config;if(d&&d.noCookies)return"";d=new Date;d.setTime(p()+c*1E3);a=a+"="+b+("; expires="+d.toGMTString())+"; path=/";return document.cookie=a};R.remove=function(a){return R.B(a)?R.create(a,"",-86400):""};var T={};T.F=function(a){var b=l._sf_async_config;if(!a&&b&&b.noCookies)return i;if(T.F.Va!==g)return T.F.Va;var a=p()+"",c,d;try{if((d=l.localStorage).setItem(a,a),c=d.getItem(a)===a,d.removeItem(a),c)return T.F.Va=d}catch(e){}return T.F.Va=i};T.B=function(a){var b=T.F();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&p()>c)?(T.remove(a),""):b.getItem(a)||""};
T.create=function(a,b,c){var d=T.F();if(d){var e=new Date;e.setTime(p()+c*1E3);try{d.setItem(a,b),d.setItem(a+"_expires",e.getTime())}catch(f){}}};T.remove=function(a){var b=T.F();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function yb(a){this.Ka=a||"";this.Zb=T.F()!==i||R.Xb();this.lb=j;zb(this)}k=yb.prototype;k.isSupported=function(){return this.Zb};
function zb(a){if(!R.B("_cb_ls")){var b=T.F()!==i,c=R.B("_SUPERFLY_nosample");c&&o(["","_v_","_p_"],function(b){a.create(b+"_SUPERFLY_nosample",c,600,h)});var d=R.B("_chartbeat3");d&&(a.create("_v__chartbeat3",d,2592E3,h),R.remove("_chartbeat3"));b&&((b=R.B("_chartbeat2"))&&a.create("_chartbeat2",b,94608E3,h),(b=R.B("_chartbeat_uuniq"))&&a.create("_chartbeat_uuniq",b,94608E3,h),(b=R.B("_chartbeat5"))&&a.create("_chartbeat5",b,60,h));R.create("_cb_ls","1",2592E3)}}
function Ab(a){var b=a.lb;a.lb=j;return b}k.create=function(a,b,c,d){a=d?a:this.Ka+a;(T.F()?T:R).create(a,b,c);T.F()&&R.create(a,b,c)};k.update=function(a,b,c,d,e,f,m){a=d?a:this.Ka+a;e=y(e)?e:"::";d=(d=this.B(a,h))?d.split(e):[];if(m&&d.length){var q=m(b),n=ka(d,function(a){return m(a)===q});n!==-1&&d.splice(n,1)}v(f)&&d.length>=f&&d.splice(0,d.length-f+1);d.push(b);this.create(a,d.join(e),c,h)};
k.B=function(a,b){var a=b?a:this.Ka+a,c=(T.F()?T:R).B(a);if(!c&&T.F()&&(c=R.B(a))&&R.B("_cb_ls")){this.lb=h;var d;switch(a){case "_SUPERFLY_nosample":d=600;break;case "_chartbeat4":d=3600;break;case "_cb_cp":d=3600;break;case "_chartbeat3":d=2592E3;break;default:d=94608E3}T.create(a,c,d)}return c};k.remove=function(a,b){a=b?a:this.Ka+a;(T.F()?T:R).remove(a);T.F()&&R.remove(a)};function Bb(a){var b=i;if(a&&(b=Cb()))return b;var c=l.location,b=U(c.pathname),a=c.search||"",a=a.replace(/PHPSESSID=[^&]+/,""),d=/&utm_[^=]+=[^&]+/ig;(c=d.exec(c.search))&&(a=a.replace(d,""));d=/\?utm_[^=]+=[^&]+(.*)/i;(c=d.exec(a))&&(a=a.replace(d,c[1]!=""?"?"+c[1]:""));return b+a}function Cb(){var a=i;o(document.getElementsByTagName("link"),function(b){if(b.rel=="canonical")return b=$a(b.href),a=U(b.pathname)+b.search+b.hash,j});return a}
for(var Db={},Eb=0;Eb<81;Eb++)Db["0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._~!$&'()*+,;=:@[]".charCodeAt(Eb)]=h;function Fb(a,b){if(a==="%")return"%25";var c=parseInt(b,16);return Db[c]?String.fromCharCode(c):"%"+b.toUpperCase()}function U(a){if(!y(a))return a;a=a.replace(/%([0-9A-Fa-f]{2})?/g,Fb);return a=a.replace(/[^0-9A-Za-z\-._~!$&'()*+,;=:@\/\[\]?#%]+/g,encodeURIComponent)};function W(){J.call(this);this.ha=[];this.D=new yb(this.Mb);this.H=new nb;this.ib=r(this.la,this);u(l,"unload",this.ib);Va(r(this.q,this))}aa(W,J);k=W.prototype;k.Ma=h;
k.q=function(){W.T.q.call(this);this.Fa=this.ca=0;this.fa=p();this.wa=da(Gb(this));var a=(this.D.B("_chartbeat2",h)||"").split("."),b=p(),c=b-+(a[1]||0);b-=+(a[2]||0);this.qc=a[0]&&c>18E5&&b<2592E6?0:1;this.ma=h;this.Ga=72E5;if(this.Ma&&(a=+this.k.sessionLength,!isNaN(a)))this.Ga=a*6E4;a=(this.D.B("_chartbeat2",h)||"").split(".");a.length>4&&(a=[]);var c=p(),d="1",e=a&&+a[2],b=a&&a[3];if(a&&e&&b)if(d=Math.abs((ha(c)-ha(e))/864E5)){d=Math.min(d,16)-1;for(e="";d--;)e+=0;d=(b+e+"1").slice(-16)}else d=
b;b=d;a[0]||(a[0]=this.k.utoken||da(Gb(this),3),a[1]=c);a[2]=c;a[3]=b;this.Pa=a[0];this.vc=a.join(".");this.D.create("_chartbeat2",this.vc,94608E3,h);this.k.utoken=this.Pa;var f;c=+a[1];b=+a[2];if((a=a[3])&&c&&b)f=(Math.min((Math.abs((ha(b)-ha(c))/864E5)||0)+1,16,a.length)-1).toString(16),f+=("0000"+parseInt(a,2).toString(16)).slice(-4);this.zb=f;this.H.q();O.q();H.q();Ka||(La=Ta(),Ma&&l.document.addEventListener&&l.document.addEventListener(Ma,Ua,j),Sa("focus","onfocusin",Qa),Sa("blur","onfocusout",
Ra),La&&Qa(),Ka=h);this.sa=0;this.Tb=G.G(Ia,this.hb,this)};function Hb(a){if(!a.D.B("_SUPERFLY_nosample")&&!I)a.pc?a.Na():(a.pc=h,!l._sf_async_config&&!l._cbq?(a.Ia=r(a.Na,a),u(l,"load",a.Ia)):a.Na())}k.Na=function(){var a=l._sf_startpt,b=l._sf_endpt;if(v(a))this.jb=v(b)?b-a:p()-a;H.q();a=r(this.ta,this);this.cb=qa(a,15E3);this.ta()};
k.ta=function(){var a=this.H.ka,a=this.k.reading&&+this.k.reading||a>0;if(this.Fa<this.ca&&!a)this.Fa++;else{var b;if(oa===g)b=l.navigator.userAgent,oa=b.indexOf("AppleWebKit")>0&&b.indexOf("FBIOS")>0;b=oa;b&&!a?this.Fa++:(a?this.ca=0:Ib(this),this.Fa=0,this.ha.push(0),this.ha.length>18&&this.ha.shift(),this.Ma&&p()-this.fa>=this.Ga?this.terminate():this.X())}};
function Jb(a){var b={};b.g=a.k.uid;b.g0=db(a.k,"sections");b.g1=db(a.k,"authors");b.g2=db(a.k,"zone");b.g3=db(a.k,"sponsorName");b.g4=db(a.k,"type");!a.k.noCookies&&a.D.isSupported()?b.n=a.qc:b.nc=1;b.c=Math.round((p()-a.fa)/600)/100;b.E=a.H.U;var c=Kb(a);a.sa=Math.max(a.sa,c);b.x=c;b.m=a.sa;b.y=F("Height");b.o=F("Width");b.w=wa("Height");b.b=a.jb?a.jb:"";if(a.zb)b.f=a.zb;b[""]=eb(a.k);b.t=a.wa;b.V=60;b.tz=(new Date).getTimezoneOffset();b.sn=a.Ja;return b}
k.Hb=function(){this.ha.push(1);var a=0;o(this.ha,function(b){a+=b});a<3?(this.ma=h,Ib(this)):(this.terminate(),this.D.create("_SUPERFLY_nosample","1",600))};k.la=function(){};k.hb=function(){var a=Kb(this);this.sa=Math.max(this.sa,a)};function Kb(a){return va("Y","Top",!!a.k.scrollElement)}function Ib(a){var b=a.ca,b=b?Math.min(b*2,16):1;a.ca=b}
k.Ra=function(a,b){if(!I)this.la(),this.terminate(),this.Aa=l.location.protocol+"//"+this.k.domain+this.k.path,this.k.path=U(a),b&&(this.k.title=b),this.q(),Hb(this)};function Lb(a){if(a.Aa)return h;a=(document.referrer||"").indexOf("://"+l.location.hostname+"/");return a!=-1&&a<9}function Mb(a){a=a.Aa;if(!a&&(a=document.referrer||"")){var b=$a(a);if(b.protocol==="http:"||b.protocol==="https:")b.pathname=U(b.pathname),a=ab(b)}return encodeURIComponent(a)}
function Nb(a){a=a.k.title.slice(0,100);return encodeURIComponent(a)}function Gb(a){a=[Mb(a),F("Width"),F("Height")];return fa(a)}function Ob(a){var b=[],c=a.D.B("_chartbeat4");c&&(o(c.split("::"),function(a){b.push(encodeURIComponent(a))}),a.D.remove("_chartbeat4"));return b}k.terminate=function(){this.H.terminate();G.Q(this.Tb);this.Ia!==g&&ga("load",this.Ia);C(this.cb)};k.Z=function(){this.terminate();ga("unload",this.ib);this.ib=this.Ia=this.D=this.ha=this.k=i;this.H.Z();this.H=i;W.T.Z.call(this)};function Pb(a){var b=Qb();return s(g)&&!s(b[a])?g:b[a]}function Qb(){s(l._cb_shared)||(l._cb_shared={});return l._cb_shared};function X(){this.Y=[];this.La=[];this.Ea=r(this.Ea,this);"postMessage"in window&&u(window,"message",r(this.kc,this));this.Mb="_p_";this.Ma=j;u(l,"beforeunload",r(this.tc,this));var a=0,b=(l.location.search||"").match(Ja);b&&b[1]&&(a=parseInt(b[1],10));if(a>0)a=r(this.Ba,this),Qb().a=a,a="ad_debug",b="//static.chartbeat.com",Ca()&&(b="//static2.chartbeat.com"),b=[b,"js"],Ca()&&(a+="dev"),b.push("chartbeat_"+a+".js"),Ba(b.join("/"));W.call(this)}aa(X,W);
X.prototype.q=function(){X.T.q.call(this);var a=l.location;M(this.k,"pingServer","ping.chartbeat.net");M(this.k,"endServer","edge01.chartbeat.net");M(this.k,"title",document.title);M(this.k,"domain",a.hostname);M(this.k,"path",Bb(!!this.k.useCanonical));M(this.k,"engaged",j);this.ba=this.k.adIdentifier||"data-cb-ad-id";this.k.domain=t(this.k.domain);this.da=this.D.B("_chartbeat2",h);this.ia=this.Bb=0;this.ec=function(){var a=p()-this.Bb;if(a<500){this.ia&&D(this.ia);var b=r(this.X,this);this.ia=ra(b,
500-a)}else this.ma||this.X()};this.dc=G.G("p",this.ec,this);if(!this.da)this.k.utoken?this.da=this.k.utoken:(this.da=da(Gb(this),3),this.k.utoken=this.da);this.da=this.da.split(".")[0];this.ya();if((a=this.k.engagedAdFilters)&&a.length){this.k.engagedAdFilters=[];var b=this;o(a,function(a){b.Ca(a)})}this.bc=G.G("e",this.$b,this);this.Gc=G.G("z",this.Dc,this);this.La=[]};X.prototype.Ba=function(a,b){var c=sa(G,Ha),d=sa(O,mb);a.injectDependencies(c,d);b.injectDependencies(c);new a;qb=b;o(this.Y,function(a){a.Ba()})};
X.prototype.tc=function(){this.X(h)};X.prototype.la=function(){this.D.update("_chartbeat4",["t="+this.wa,"E="+this.H.U,"ad="+ia(Rb(this,h)),"x="+Kb(this),"c="+Math.round((p()-this.fa)/600)/100,"y="+F("Height"),"w="+wa("Height")].join("&"),3600,g,g,1)};function Rb(a,b){var c=[];o(a.Y,function(a){a=sb(a);(!b||!(a.aw<=1&&a.ah<=1))&&c.push(xb(a))});return c.concat(a.La).join("&")}var Sb="h,p,u,d,g,g0,g1,g2,g3,g4,n,nc,f,c,x,m,y,o,w,j,E,v,r,vp,b,t,V,i,tz,l,,ad,z,zz,sn".split(",");k=X.prototype;
k.X=function(a){this.Ja++;var b=this.Ea();b.ad=ia(Rb(this));this.Bb=p();this.ia&&D(this.ia);Bb(!!this.k.useCanonical);if(this.ma)this.ma=j,b.i=Nb(this);this.Aa&&(b.vp=1);var c=0;a?(b.zz=1,a=this.k.endServer):(b.z=Ob(this),c=Math.round((this.ca+2)*15E3/1E3),a=this.k.pingServer);b.j=c;b.l=Ab(this.D)?1:"";this.H.ka=0;this.va("https://"+a+"/ping/ad?"+Za(b,Sb))};
k.Ea=function(){var a=Jb(this),b=l.location;a.h=encodeURIComponent("ads."+this.k.domain);a.p=encodeURIComponent(this.k.path);a.u=this.da;a.d=ia(t(b.hostname));Lb(this)?a.v=Mb(this):a.r=Mb(this);return a};function Tb(a){var b=ta(a.ba,"div");o(b,function(b){if(!Ub(a,b)){var d=new P(b,a.Ea);a.Y.push(d);d.ya();if(b=E("data-cb-engaged-seconds",b))d=wb(d),d.engagedSeconds=parseInt(b,10),a.Ca(d)}})}function Ub(a,b){var c;o(a.Y,function(a){if(a.aa===b||a.J===b)return c=a,j});return c}
k.ya=function(){var a=Pb("c");Tb(this);var b=this;o(this.Y,function(c){c.ya();var d=c.aa;if(a&&a[d]){var e=-1;o(a[d],function(a,d){if(a.e===c.J)return a.c(b.wa),e=d,j});e>-1&&a[d].splice(e,1)}})};k.hb=function(){X.T.hb.call(this);Tb(this)};k.kc=function(a){this.Cb(ma(a.data),a.source)};
k.Cb=function(a,b){if(a.cbType!=="campaignMessage")return j;var c=b;if(c.parent!=window){for(var d=0;c.parent!=window&&d<10;)c=c.parent,d++;if(d>=10)return j}Tb(this);var d=document.getElementsByTagName("iframe"),e=g;o(d,function(a){if(a.contentWindow===c)return e=a,j});if(!e)return j;var f=e.getAttribute(this.ba),m;if(f===i){m=ua(e,this.ba);if(!m)return j;f=m.getAttribute(this.ba)}else m=e;var q=g;o(this.Y,function(a){if(f===a.aa&&m===a.J)return q=a,j});if(q===g)return j;vb(q,a,e);if(a.engagedSeconds)d=
{id:q.aa},d.campaignId=a.campaignId,d.creativeId=a.creativeId,d.engagedSeconds=parseInt(a.engagedSeconds,10),this.Ca(d);d="cbdata::ack::"+this.wa;"postMessage"in b&&b.postMessage(d,"*");return d};k.Hc=function(){this.la();this.terminate();this.Aa=l.location.protocol+"//"+this.k.domain+this.k.path};k.Ra=function(){this.q();Hb(this);Vb()};function Vb(){bb("_cba",function(a){a()})}
k.Ca=function(a){if(a&&v(a.engagedSeconds)&&!isNaN(a.engagedSeconds)){var b=this.k.engagedAdFilters;if(!b||b.length===g)this.k.engagedAdFilters=[],b=this.k.engagedAdFilters;var c={};c.engagedSeconds=a.engagedSeconds;o(["id","campaignId","creativeId"],function(b){y(a[b])&&(c[b]=a[b])});var d=j;o(b,function(a){d=ja(a,c);return!d});d||b.push(c)}};
k.xc=function(a,b){if(!a)return j;var c=l.document.getElementById(b);if(!c)return j;var d;c.getAttribute(this.ba)&&(d=Ub(this,c));var e=this;if(!d){var f=ta(this.ba,"div",c);o(f,function(a){if(d=Ub(e,a))return j})}d||(c=ua(c,this.ba))&&(d=Ub(this,c));if(!d)return j;d.Ab=a;return h};
k.$b=function(a){if(a){var b=this.k.engagedAdFilters;if(b&&b.length){var c=a.Ab,d=this.k.engagedAdCallback;c&&!d&&(d=pa);if(d){var e=this,f=wb(a),m=f.engagedSeconds;o(b,function(b){if(b.engagedSeconds===m){var n=h;o(b,function(a,b){return n=a===f[b]});if(n)return f.element=a.J,d(f,m),c&&a.fb==j&&Wb(e,a),j}})}}}};k.wc=function(a){if(a&&(a=Ub(this,a))){a.Ua=1;var b=sb(a);this.La.push(xb(b));a.refresh();a.Ta=1}};
function Wb(a,b){b.Ua=2;var c=sb(b);a.La.push(xb(c));b.refresh();c=b.Ab;try{c.setTargeting("_cbr","1"),l.googletag.pubads().refresh([c]),b.Ta=2}catch(d){}}k.Dc=function(a,b){for(var c=ma(this.D.B("_chartbeat7")),d=parseInt(c[a.vzcid],10)||0,e={1:h,5:h,15:h,30:h,60:h,100:h};b--;)if(d++,e[d+""]){var f=a,m=d+"second"+(d!==1?"s":""),q=da(ca());ba("http://ohlone.vizu.com/a.gif?vzcid="+f.vzcid+"&vzadid="+m+"&vzsid="+f.vzsid+"&ord="+q)}c[a.vzcid]=d;this.D.create("_chartbeat7",la(c),94608E3)};
k.terminate=function(){G.Q(this.dc);G.Q(this.bc);G.Q(this.Gc);o(this.Y,function(a){a.Z()});l._cba=[];this.Y=[];D(this.ia);X.T.terminate.call(this)};if(!l.pSUPERFLY_pub){var Y=new X;l.pSUPERFLY_pub={willVirtualPage:r(Y.Hc,Y),virtualPage:r(Y.Ra,Y),addEngagedAdFilter:r(Y.Ca,Y),refreshAd:r(Y.wc,Y),updateCampaignData:r(Y.ya,Y),registerGptSlot:r(Y.xc,Y)};"postMessage"in window!==h&&(l.pSUPERFLY_pub.loadCampaign=r(Y.Cb,Y));Hb(Y)};var Xb,Yb,Zb;function $b(a){if(a.origin==="https://chartbeat.com"&&(a=String(a.data),a.indexOf("_cb_hud_version=")===0&&(a=a.substr(16),ac(),a!=="NONE"))){var a=a.indexOf("HUD2.")===0?a.substr(5):"OLD",b="https://static.chartbeat.com/js/inpage.js";a!=="OLD"&&(b="https://static2.chartbeat.com/frontend_ng/hud/hud-inpage/hud-inpage-"+a+".js");Ba(b)}}function ac(){D(Yb);Yb=g;ga("message",$b);Zb&&Zb.parentNode&&Zb.parentNode.removeChild(Zb);Zb=g};function bc(){var a=l._sf_async_config&&l._sf_async_config.domain;if(a&&!Xb){Xb=h;a="https://chartbeat.com/publishing/hud2/versioninfo/?host="+encodeURIComponent(a);u(l,"message",$b);Yb=ra(ac,1E4);var b=s(g)?g:{};b.src=a;a=Aa("iframe",b);a.style.display="none";s(g)?g.appendChild(a):document.body&&document.body.appendChild(a);Zb=a}}
function cc(a){if(/[\/.]chartbeat\.com$/.test(a.origin)){var b=T.F(h),c=String(a.data);b&&c.indexOf("_cb_ip")==0&&(b.setItem("_cb_ip","1"),a.source.postMessage(1,a.origin),bc(),ga("message",cc))}};function dc(a,b){for(var c=b||document.documentElement,d=[],e=i,f=a,m,q,n,z,x,K;f&&f!==c;){m=f.nodeName.toLowerCase();e=f;q=e.nodeName;if((f=f.parentNode)&&f!==document.documentElement){n=f.children;z=0;for(x=0,K=n.length;x<K;x++){if(e===n[x]){m+="["+(1+x-z)+"]";break}n[x].nodeName!==q&&z++}}d.unshift(m)}return d.join("/")};function Z(){"postMessage"in window&&u(l,"message",r(this.jc,this));W.call(this);bb("_cbq",r(this.Ib,this))}aa(Z,W);Z.prototype.q=function(){Z.T.q.call(this);this.Sa=i;cb(this.k);var a=l.location;M(this.k,"pingServer","ping.chartbeat.net");M(this.k,"title",document.title);M(this.k,"domain",a.hostname);this.k.path=this.k.path?U(this.k.path):Bb(!!this.k.useCanonical);this.qa=t(a.hostname);this.k.domain=t(this.k.domain);this.Vb=G.G("c",this.rc,this);this.Wb=G.G("r",this.sc,this);this.ja=i};
Z.prototype.Sb=function(a){this.Sa=a};Z.prototype.la=function(){this.D.update("_chartbeat4",["t="+this.wa,"E="+this.H.U,"x="+Kb(this),"c="+Math.round((p()-this.fa)/600)/100,"y="+F("Height"),"w="+wa("Height")].join("&"),3600,g,g,1)};var ec="h,p,u,d,g,g0,g1,g3,g4,n,nc,f,c,x,m,y,o,w,j,R,W,I,E,e,v,r,vp,K,l1,KK,PA,b,A,_c,_m,t,V,z,i,L,tz,l,,sn,C,eS,eM,eD,eK,eR".split(",");k=Z.prototype;
k.X=function(a){this.Ja++;var b=Jb(this),c=this.H.ka;b.h=encodeURIComponent(this.k.domain);b.p=encodeURIComponent(this.k.path);b.u=this.Pa;b.d=encodeURIComponent(this.qa);b.j=Math.round((this.ca+2)*15E3/1E3);b.R=0;b.W=0;b.I=0;var d=b.c*6E4+this.fa;b.eD=H.oa("mousedown",d);b.eM=H.oa("mousemove",d);b.eK=H.oa("keydown",d);b.eR=H.oa("resize",d);b.eS=H.oa("scroll",d);H.yc();H.Ub()?b.W=1:this.k.reading&&+this.k.reading||c>0||b.c<0.09?b.R=1:b.I=1;b.e=c;c=Lb(this);if(this.ma)this.ma=j,c?this.ja=fc(this):
b.r=Mb(this),b.i=Nb(this),d=this.k.hudTrackable,d!==g&&(b.L=d?"1":"0"),this.k.alias&&(b.PA=encodeURIComponent(this.k.alias));if(c){if(this.ja){if(b.v=encodeURIComponent(this.ja.path),b.K=hc(this.ja),this.ja.gb>1)b.l1=this.ja.gb}else b.v=Mb(this);this.Aa&&(b.vp=1)}b.A=this.Sa?this.Sa:"";b._c=Xa("utm_campaign",this.k.campaignTag);b._m=Xa("utm_medium",this.k.mediumTag);b.z=Ob(this);b.C=this.k.mobileApp?1:"";b.KK=a?hc(a,h):"";b.l=Ab(this.D)?1:"";this.H.ka=0;this.va((l.location.protocol||"http:")+"//"+
this.k.pingServer+"/ping?"+Za(b,ec))};
k.jc=function(a){var b=this.k;if(a.origin==="http://"+(b.playerdomain||this.qa)){var c=a.data;y(c)&&c.indexOf("cbqpush::")===0?(a=c.split("::"),a.length==3&&(a=a.slice(1),a[0].indexOf("_")===0&&this.Ib(a))):c=="cbdata?"&&(b="domain="+encodeURIComponent(b.domain)+"&uid="+encodeURIComponent(b.uid)+"&path="+encodeURIComponent(b.path)+"&title="+Nb(this)+"&referrer="+Mb(this)+"&internal="+(Lb(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.qa)+"&utoken="+this.Pa,a.source.postMessage(b,"*"))}};
k.Ib=function(a){a[0]==="_demo"&&this.k._demo?this.k._demo=this.k._demo+"%2C"+a[1]:this.k[a[0]]=a[1];this.ca=0};function ic(a){a=a.replace(/-{2,}/g,"-");a=$a(a);a.pathname=U(a.pathname);return a}k.rc=function(a){jc(this,a,"c")};k.sc=function(a){jc(this,a,"r")};
function jc(a,b,c){if(a.Ma&&p()-a.fa>=a.Ga)a.terminate();else{var d=b.href||"",d=ic(d);if(!(d.hostname!==l.location.hostname||d.protocol.indexOf("http")!==0)){var d=ab(d),e=xa(b,function(a){return a.id}),f=dc(b,e);e&&(f&&(f="/"+f),f="*[@id='"+e.id+"']"+f);e=da(f);b=jb(b,g,h);c={left:b.x,top:b.y,path:a.k.path,href:d,rb:e,qb:f,kb:c,gb:0};a.X(c);a.D.update("_chartbeat5",kc(c),60,j,g,5,function(a){a=a.split(",");return a[2]+","+a[3]})}}}
function hc(a,b){var c=[a.left,a.top,a.rb,encodeURIComponent(a.qb),a.kb];b&&c.push(encodeURIComponent(a.href));return c.join("::")}function kc(a){var b=encodeURIComponent(a.qb),b=b.replace(/-/g,"%2D");b.length>512&&(b="");return[a.left,a.top,encodeURIComponent(a.path),encodeURIComponent(a.href),a.rb,b,a.kb].join(",")}
function fc(a){var b=a.D.B("_chartbeat5");if(!b)return i;var c=b.split("::"),b=c.length,d,e;if(b===1)d=c[0].split(","),e=0;else{var f,m=ic(l.location.href),q=ab(m);o(c,function(a,b){var c=a.split(","),m=na(q,decodeURIComponent(c[3]));if(m===0)return d=c,e=b,j;if(f===g||m<f)f=m,d=c,e=b})}c.splice(e,1);a.D.create("_chartbeat5",c.join("::"),60);(a=d[5])?(a=a.replace(/%2D/g,"-"),a=decodeURIComponent(a)):a="";return{left:d[0],top:d[1],path:decodeURIComponent(d[2]),rb:d[4]||"",qb:a,kb:d.length>6?d[6]:"c",
gb:b}}k.terminate=function(){G.Q(this.Vb);G.Q(this.Wb);Z.T.terminate.call(this)};if(!l.pSUPERFLY){var lc=new Z;l.pSUPERFLY={virtualPage:r(lc.Ra,lc),activity:r(lc.Sb,lc)};var $=l.pSUPERFLY_pub;if($)$.virtualPage&&(l.pSUPERFLY.virtualPage=function(){var a=arguments.length?Array.prototype.slice.call(arguments,0):[];$.willVirtualPage();Z.prototype.Ra.apply(lc,a);$.virtualPage()}),$.addEngagedAdFilter&&(l.pSUPERFLY.addEngagedAdFilter=$.addEngagedAdFilter),$.refreshAd&&(l.pSUPERFLY.refreshAd=$.refreshAd),$.registerGptSlot&&(l.pSUPERFLY.registerGptSlot=$.registerGptSlot),bb("_cba",function(a){a()});
Hb(lc);var mc=T.F(h);if(mc)if(mc.getItem("_cb_ip")){var nc=l.location;(!/^(.+[.])?chartbeat\.com$/.test(nc.hostname)?0:/^\/publishing\/(overlay|hud|mab)\//.test(nc.pathname))||bc()}else u(l,"message",cc)};function oc(){var a=l.location.href,a=a.replace(/-{2,}/g,"-"),a=$a(a);a.pathname=U(a.pathname);return a}function pc(a){var b=R.B("_chartbeat6");if(!b)return i;var b=b.split("::"),c,d;if(b.length===1)c=b[0].split(","),d=0;else{var e,f=oc(),m=ab(f);o(b,function(a,b){var f=a.split(","),x=na(m,decodeURIComponent(f[0]));if(x===0)return c=f,d=b,j;if(e===g||x<e)e=x,c=f,d=b})}b.splice(d,1);a="_chartbeat6="+b.join("::")+qc(a);document.cookie=a;return{Kc:c[0],cc:c[1],Ec:c[2],origin:c[3]}}
function qc(a){var b="",c;if(!B(a))return b;a.Fb&&(c=new Date,c.setTime(c.getTime()+a.Fb),b+="; expires="+c.toGMTString());a.domain&&(b+="; domain="+a.domain);a.path&&(b+="; path="+a.path);return b}function rc(a,b){if(a===b)return h;for(var c=b.split("."),d=a.split(".");c.length;){if(d.length===0)return j;if(c.pop()!==d.pop())return j}return h};function sc(){this.Mb="_t_";W.call(this)}aa(sc,W);k=sc.prototype;
k.q=function(){sc.T.q.call(this);cb(this.k);var a=l.location;M(this.k,"mabServer","mabping.chartbeat.net");M(this.k,"title",document.title);M(this.k,"domain",a.hostname);M(this.k,"path",Bb(!!this.k.useCanonical));this.qa=t(a.hostname);this.k.domain=t(this.k.domain);var b=this.k,a=b.topStorageDomain,b=b.domain,c=l.location.hostname;this.Bc=a?a:rc(c,b)?b:c.replace(/^www\./,"");this.Ob=this.xb=this.yb="";this.Da=this.eb=j;a=pc({domain:"."+this.Bc,Fb:6E4,path:"/"});if(a!==i)this.yb=a.origin,this.xb=a.cc,
this.Ob=a.Ec,this.eb=h;this.Ga=6E4;this.Gb=0;a=r(this.lc,this);for(b=Pb("m")||[];b.length;)a(b.shift());a={push:a};Qb().m=a};k.X=function(){var a=this.H.U,b=tc(this),c,d,e;if(this.eb)c=this.yb,d=this.xb,e=this.Ob,this.va(b+"&x="+d+"&v="+e+"&xo="+c+"&e="+a);!this.Da&&s(this.Nb)&&uc(this,this.Nb);this.Da=h};k.Na=function(){var a=l._sf_startpt,b=l._sf_endpt;if(v(a))this.jb=v(b)?b-a:p()-a;H.q();if(this.eb)this.cb=l.setInterval(r(this.ta,this),500);this.ta()};
k.ta=function(){var a,b;this.Da?(a=this.H.U,b=this.Gb*15,a-b>=15&&(this.X(),this.Gb+=1),a>=45&&l.clearInterval(this.cb)):this.X()};function tc(a){var b=a.k;return(l.location.protocol||"http:")+"//"+b.mabServer+"/ping/mab?h="+encodeURIComponent(b.domain)+"&p="+encodeURIComponent(b.path)+"&d="+encodeURIComponent(a.qa)+"&u="+a.Pa+"&c="+Math.round((p()-a.fa)/600)/100}k.la=function(){};
k.Ac=function(a){var b=a.d,c=i;b!==i&&(c={Kb:b.s,oc:b.l,Eb:b.m});a={status:a.s,data:c,code:a.c,message:a.m};this.Da?uc(this,a):this.Nb=a};function uc(a,b){var c=tc(a),d=b.status,e=b.data;if(d=="s"&&e!==i){if(!e.oc){var f=r(a.va,a);B(e.Kb)&&o(e.Kb,function(a,b){f(c+"&x="+b+"&v="+a+"&e=-1")});Object.prototype.toString.call(e.Eb)==="[object Array]"&&o(e.Eb,function(a){f(c+"&mt=e&me=3&x="+a)})}}else d=="e"&&a.va(c+"&mt=e&me="+b.code)}
k.lc=function(a,b){for(var c=0,d=arguments.length;c<d;c++)a=arguments[c],a.shift()==="t"&&this.Ac.apply(this,a)};if(!l.pSUPERFLY_mab)l.pSUPERFLY_mab={},Hb(new sc);})();
