// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 3
(function(w,g){w[g]=w[g]||{};w[g].e=function(s){return eval(s);};})(window,'google_tag_manager');(function(){
var O=this,pa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var d=Object.prototype.toString.call(a);if("[object Window]"==d)return"object";if("[object Array]"==d||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==d||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b},ra=function(a,b){var d=Array.prototype.slice.call(arguments,1);return function(){var b=d.slice();b.push.apply(b,arguments);return a.apply(this,b)}},sa=null;/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var ua=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,wa=function(a){if(null==a)return String(a);var b=ua.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},xa=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},fa=function(a){if(!a||"object"!=wa(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!xa(a,"constructor")&&!xa(a.constructor.prototype,"isPrototypeOf"))return!1}catch(b){return!1}for(var d in a);return void 0===
d||xa(a,d)},ya=function(a,b){var d=b||("array"==wa(a)?[]:{}),c;for(c in a)if(xa(a,c)){var e=a[c];"array"==wa(e)?("array"!=wa(d[c])&&(d[c]=[]),d[c]=ya(e,d[c])):fa(e)?(fa(d[c])||(d[c]={}),d[c]=ya(e,d[c])):d[c]=e}return d};var za=function(){},K=function(a){return"function"==typeof a},P=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},Aa=function(a){return"number"==wa(a)&&!isNaN(a)},Ba=function(a,b){if(Array.prototype.indexOf){var d=a.indexOf(b);return"number"==typeof d?d:-1}for(var c=0;c<a.length;c++)if(a[c]===b)return c;return-1},Ca=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},L=function(a){return Math.round(Number(a))||0},ha=function(a){return"false"==String(a).toLowerCase()?!1:
!!a},Da=function(a){var b=[];if(P(a))for(var d=0;d<a.length;d++)b.push(String(a[d]));return b},J=function(){return new Date},Ea=function(a,b){if(!Aa(a)||!Aa(b)||a>b)a=0,b=2147483647;return Math.round(Math.random()*(b-a)+a)},Fa=function(){this.prefix="gtm.";this.values={}};Fa.prototype.set=function(a,b){this.values[this.prefix+a]=b};Fa.prototype.get=function(a){return this.values[this.prefix+a]};Fa.prototype.contains=function(a){return void 0!==this.get(a)};
var Ga=function(a,b,d){try{return a["3"](a,b||za,d||za)}catch(c){}return!1},Ha=function(a,b){function d(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var c=Ca(b).split("&"),e=0;e<c.length;e++)if(c[e]){var f=c[e].indexOf("=");0>f?d(c[e],"1"):d(c[e].substring(0,f),c[e].substring(f+1))}},Ia=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},Ja=function(a){for(var b=0;b<a.length;b++)a[b]()},da=J().getTime(),ga=function(a,b,d){return a&&a.hasOwnProperty(b)?a[b]:d},Ka=function(a,
b,d){a.prototype["gtm_proxy_"+b]=a.prototype[b];a.prototype[b]=d},Na=function(a){return null!==a&&void 0!==a&&void 0!==a.length},ea=function(a,b,d){if(!(b&&d&&Na(a)&&P(a)&&0!=a.length))return null;for(var c={},e=0;e<a.length;e++)a[e]&&a[e].hasOwnProperty(b)&&a[e].hasOwnProperty(d)&&(c[a[e][b]]=a[e][d]);return c};var x=window,N=document,Oa=navigator,I=function(a,b,d){var c=x[a];if(a&&/^[a-zA-Z_]\w*$/g.test(a)){var e="var "+a+";";if(O.execScript)O.execScript(e,"JavaScript");else if(O.eval)if(null==sa&&(O.eval("var _et_ = 1;"),"undefined"!=typeof O._et_?(delete O._et_,sa=!0):sa=!1),sa)O.eval(e);else{var f=O.document,g=f.createElement("SCRIPT");g.type="text/javascript";g.defer=!1;g.appendChild(f.createTextNode(e));f.body.appendChild(g);f.body.removeChild(g)}else throw Error("goog.globalEval not available");}x[a]=
void 0===c||d?b:c;return x[a]},M=function(a,b,d,c){return(c||"http:"!=x.location.protocol?a:b)+d},Pa=function(a){var b=N.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)},ia=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},C=function(a,b,d){var c=N.createElement("script");c.type="text/javascript";c.async=!0;c.src=a;ia(c,b);d&&(c.onerror=d);Pa(c)},ba=function(a,b){var d=N.createElement("iframe");
d.height="0";d.width="0";d.style.display="none";d.style.visibility="hidden";Pa(d);ia(d,b);void 0!==a&&(d.src=a);return d},p=function(a,b,d){var c=new Image(1,1);c.onload=function(){c.onload=null;b&&b()};c.onerror=function(){c.onerror=null;d&&d()};c.src=a},R=function(a,b,d,c){a.addEventListener?a.addEventListener(b,d,!!c):a.attachEvent&&a.attachEvent("on"+b,d)},q=function(a){x.setTimeout(a,0)},ka=!1,la=[],Qa=function(a){if(!ka){var b=N.createEventObject,d="complete"==N.readyState,c="interactive"==
N.readyState;if(!a||"readystatechange"!=a.type||d||!b&&c){ka=!0;for(var e=0;e<la.length;e++)la[e]()}}},Ra=0,Sa=function(){if(!ka&&140>Ra){Ra++;try{N.documentElement.doScroll("left"),Qa()}catch(a){x.setTimeout(Sa,50)}}},Ua=function(a){var b=N.getElementById(a);if(b&&Ta(b,"id")!=a)for(var d=1;d<document.all[a].length;d++)if(Ta(document.all[a][d],"id")==a)return document.all[a][d];return b},Ta=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},Va=function(a){return a.target||
a.srcElement||{}},oa=function(a){var b=N.createElement("div");b.innerHTML="A<div>"+a+"</div>";for(var b=b.lastChild,d=[];b.firstChild;)d.push(b.removeChild(b.firstChild));return d},Wa=function(a,b){for(var d={},c=0;c<b.length;c++)d[b[c]]=!0;for(var e=a,c=0;e&&!d[String(e.tagName).toLowerCase()]&&100>c;c++)e=e.parentElement;e&&!d[String(e.tagName).toLowerCase()]&&(e=null);return e},Xa=!1,Ya=[],$a=function(){if(!Xa){Xa=!0;for(var a=0;a<Ya.length;a++)Ya[a]()}},ab=function(a){a=a||x;var b=a.location.href,
d=b.indexOf("#");return 0>d?"":b.substring(d+1)},ma=function(a){window.console&&window.console.log&&window.console.log(a)};var eb=function(a,b,d,c,e){var f,g=(a.protocol.replace(":","")||x.location.protocol.replace(":","")).toLowerCase();switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||x.location.hostname).split(":")[0].toLowerCase();if(d){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:x.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var l=f.split("/");0<=Ba(c||[],l[l.length-
1])&&(l[l.length-1]="");f=l.join("/");break;case "query":f=a.search.replace("?","");if(e)a:{for(var m=f.split("&"),k=0;k<m.length;k++){var n=m[k].split("=");if(decodeURIComponent(n[0]).replace("+"," ")==e){f=decodeURIComponent(n.slice(1).join("=")).replace("+"," ");break a}}f=void 0}break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},fb=function(a){var b="";a&&a.href&&(b=a.hash?a.href.replace(a.hash,""):a.href);return b},ca=function(a){var b=N.createElement("a");a&&
(b.href=a);return b};var gb=new Fa,hb={},jb={set:function(a,b){ya(ib(a,b),hb)},get:function(a){return D(a,2)},reset:function(){gb=new Fa;hb={}}},D=function(a,b){if(2==b){for(var d=hb,c=a.split("."),e=0;e<c.length;e++){if(void 0===d[c[e]])return;d=d[c[e]]}return d}return gb.get(a)},ib=function(a,b){for(var d={},c=d,e=a.split("."),f=0;f<e.length-1;f++)c=c[e[f]]={};c[e[e.length-1]]=b;return d};var kb=new RegExp(/^(.*\.)?(google|youtube|blogger)(\.com?)?(\.[a-z]{2})?\.?$/),lb={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},mb={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},nb=function(a,b){for(var d=[],c=0;c<a.length;c++)d.push(a[c]),d.push.apply(d,b[a[c]]||[]);return d},ob=function(){var a=D("gtm.whitelist");
var b=a&&nb(Da(a),lb),d=D("gtm.blacklist")||D("tagTypeBlacklist")||[];kb.test(x.location&&x.location.hostname)&&(d=Da(d),d.push("customScripts"));var c=d&&nb(Da(d),mb),e={};return function(f){var g=f&&f["3"];if(!g)return!0;if(void 0!==e[g.a])return e[g.a];var h=!0;if(a)a:{if(0>Ba(b,g.a))if(g.b&&0<g.b.length)for(var l=0;l<g.b.length;l++){if(0>Ba(b,g.b[l])){h=
!1;break a}}else{h=!1;break a}h=!0}var m=!1;if(d){var k;if(!(k=0<=Ba(c,g.a)))a:{for(var n=g.b||[],r=new Fa,t=0;t<c.length;t++)r.set(c[t],!0);for(t=0;t<n.length;t++)if(r.get(n[t])){k=!0;break a}k=!1}m=k}return e[g.a]=!h||m}};var S=function(a){var b=N;return pb?b.querySelectorAll(a):null},qb;a:{var rb=/MSIE +([\d\.]+)/.exec(Oa.userAgent);if(rb&&rb[1]){var sb=N.documentMode;sb||(sb="CSS1Compat"==N.compatMode?parseInt(rb[1],10):5);if(!sb||8>=sb){qb=!1;break a}}qb=!!N.querySelectorAll}var pb=qb;var _et=function(a){var b=D("gtm.element"),d;if(b){var c=b.innerText||b.textContent||"";c&&" "!=c&&(c=c.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));c&&(c=c.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));d=c}else d="";var e=d;return e?e:a[""]};_et.a="et";_et.b=["google"];var _eu=function(a){var b=String(D("gtm.elementUrl")||a[""]||""),d=ca(b);return b};_eu.a="eu";_eu.b=["google"];var tb=Math.random(),ub=null,vb=null,T={};var _e=function(){return vb};_e.a="e";_e.b=["google"];var _v=function(a){var b=D(a["5"].replace(/\\\./g,"."),a[""]);return void 0!==b?b:a[""]};_v.a="v";_v.b=["google"];var _f=function(a){var b=String(D("gtm.referrer")||N.referrer);if(!b)return b;var d=ca(b);return b};_f.a="f";_f.b=["google"];var aa=function(a){var b=x.location,d=b.hash?b.href.replace(b.hash,""):b.href,c;if(c=a[""]?a[""]:D("gtm.url"))d=String(c),b=ca(d);var e,f,g;
a["2"]&&(d=eb(b,a["2"],e,f,g));return d},_u=aa;_u.a="u";_u.b=["google"];var _eq=function(a){return String(a["0"])==String(a["1"])};_eq.a="eq";_eq.b=["google"];var _re=function(a){return(new RegExp(a["1"],a[""]?"i":void 0)).test(a["0"])};_re.a="re";_re.b=["google"];var Cb=Math.random(),Db="1.000000">Cb;var Eb=za;var Fb=za,Gb=[],Hb=!1,Ib=function(a){return x["dataLayer"].push(a)},Jb=function(a){var b=!1;return function(){!b&&K(a)&&q(a);b=!0}},Qb=function(){for(var a=!1;!Hb&&0<Gb.length;){Hb=!0;var b=Gb.shift();if(K(b))try{b.call(jb)}catch(d){}else if(P(b))a:{var c=b;if("string"==wa(c[0])){for(var e=c[0].split("."),f=e.pop(),g=c.slice(1),h=hb,l=0;l<e.length;l++){if(void 0===h[e[l]])break a;h=h[e[l]]}try{h[f].apply(h,g)}catch(m){}}}else{var k=b,n=void 0;for(n in k)if(k.hasOwnProperty(n)){var r=n,t=k[n];
gb.set(r,t);ya(ib(r,t),hb)}var B=!1,u=k.event;if(u){vb=u;var A=Jb(k.eventCallback),E=k.eventTimeout;E&&x.setTimeout(A,Number(E));B=Fb(u,A,k.eventReporter)}ub||(ub=k["gtm.start"])&&Eb();vb=null;a=B||a}var V=b,Q=hb;Pb();Hb=!1}return!a};var Rb,Sb=/(Firefox\D28\D)/g.test(Oa.userAgent),Tb={nwnc:{},nwc:{},wnc:{},wc:{},wt:null,l:!1},Ub={nwnc:{},nwc:{},wnc:{},wc:{},wt:null,l:!1},$b=function(a,b){return function(d){d=d||x.event;var c=Va(d),e=!1;if(3!==d.which||"LINK_CLICK"!=a){"LINK_CLICK"==a&&(c=Wa(c,["a","area"]),e=!c||!c.href||Vb(c.href)||2===d.which||null==d.which&&4==d.button||d.ctrlKey||d.shiftKey||d.altKey||!0===d.metaKey);var f="FORM_SUBMIT"==a?Ub:Tb;if(d.defaultPrevented||!1===d.returnValue||d.da&&d.da()){if(c){var g={simulateDefault:!1},
h=Wb(f,["wnc","nwnc"]);h&&Xb(a,c,g,f.wt,h)}}else{if(c){var g={},l=!0,m=Wb(f,["wnc","nwnc","nwc","wc"]);(l=Xb(a,c,g,f.wt,m))||(Yb(g.eventReport,f)?b=!0:e=!0);e=e||l||"LINK_CLICK"==a&&Sb;g.simulateDefault=!l&&b&&!e;g.simulateDefault&&(e=Zb(c,g)||e,!e&&d.preventDefault&&d.preventDefault());d.returnValue=l||!b||e;return d.returnValue}return!0}}}},Xb=function(a,b,d,c,e){var f=c||2E3,g={"gtm.element":b,"gtm.elementClasses":b.className,"gtm.elementId":b["for"]||Ta(b,"id")||"","gtm.elementTarget":b.formTarget||
b.target||""};switch(a){case "LINK_CLICK":g["gtm.triggers"]=e||"";g.event="gtm.linkClick";g["gtm.elementUrl"]=b.href;g.eventTimeout=f;g.eventCallback=ac(b,d);g.eventReporter=function(a){d.eventReport=a};break;case "FORM_SUBMIT":g["gtm.triggers"]=e||"";g.event="gtm.formSubmit";g["gtm.elementUrl"]=bc(b);g.eventTimeout=f;g.eventCallback=cc(b,d);g.eventReporter=function(a){d.eventReport=a};break;case "CLICK":g.event="gtm.click";g["gtm.elementUrl"]=b.formAction||b.action||b.href||b.src||b.code||b.codebase||
"";break;default:return!0}return Ib(g)},bc=function(a){var b=a.action;b&&b.tagName&&(b=a.cloneNode(!1).action);return b},dc=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "area":case "form":b="_self"}return b},Zb=function(a,b){var d=!1,c=/(iPad|iPhone|iPod)/g.test(Oa.userAgent),e=dc(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;f=(e||"_self").substring(1);b.targetWindow=x.frames&&x.frames[f]||x[f];break;case "_blank":c?(b.simulateDefault=
!1,d=!0):(b.targetWindowName="gtm_autoEvent_"+J().getTime(),b.targetWindow=x.open("",b.targetWindowName));break;default:c&&!x.frames[e]?(b.simulateDefault=!1,d=!0):(x.frames[e]||(b.targetWindowName=e),b.targetWindow=x.frames[e]||x.open("",e))}return d},ac=function(a,b,d){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(d=d||J().getTime(),500>J().getTime()-d&&x.setTimeout(ac(a,b,d),25)))}},cc=function(a,b,d){return function(){if(b.simulateDefault)if(b.targetWindow){var c;
b.targetWindowName&&(c=a.target,a.target=b.targetWindowName);N.gtmSubmitFormNow=!0;ec(a).call(a);b.targetWindowName&&(a.target=c)}else d=d||J().getTime(),500>J().getTime()-d&&x.setTimeout(cc(a,b,d),25)}},Wb=function(a,b){for(var d=[],c=0;c<b.length;c++){var e=a[b[c]],f;for(f in e)e.hasOwnProperty(f)&&e[f]&&d.push(f)}return d.join(",")},fc=function(a,b,d,c,e){var f=e;if(!f||"0"==f){if(a.l)return;a.l=!0;f="0"}var g=a.wt;b&&(!g||g>c)&&(a.wt=c);a[b?d?"wc":"wnc":d?"nwc":"nwnc"][f]=!0},Yb=function(a,b){if(b.wnc["0"]||
b.wc["0"])return!0;for(var d=0;d<gc.length;d++)if(a.passingRules[d]){var c=gc[d],e=hc[d],f=e&&e[0]&&e[0][0]||e[1]&&e[1][0];if(f&&"0"!=f&&(b.wc[f]||b.wnc[f]))for(var g=c[1],h=0;h<g.length;h++)if(a.resolvedTags[g[h]])return!0}return!1},ic=function(a,b,d,c,e){var f,g,h=!1;switch(a){case "CLICK":if(N.gtmHasClickListenerTag)return;N.gtmHasClickListenerTag=!0;f="click";g=function(a){var b=Va(a);b&&Xb("CLICK",b,{},c)};h=!0;break;case "LINK_CLICK":b&&!Rb&&(Rb=fb(N.location));fc(Tb,b||!1,d||!1,c,e);if(N.gtmHasLinkClickListenerTag)return;
N.gtmHasLinkClickListenerTag=!0;f="click";g=$b(a,b||!1);break;case "FORM_SUBMIT":fc(Ub,b||!1,d||!1,c,e);if(N.gtmHasFormSubmitListenerTag)return;N.gtmHasFormSubmitListenerTag=!0;f="submit";g=$b(a,b||!1);break;default:return}R(N,f,g,h)},Vb=function(a){if(!Rb)return!0;var b=a.indexOf("#");if(0>b)return!1;if(0==b)return!0;var d=ca(a);return Rb==fb(d)},ec=function(a){try{if(a.constructor&&a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;
N.gtmFormElementSubmitter||(N.gtmFormElementSubmitter=N.createElement("form"));return N.gtmFormElementSubmitter.submit.call?N.gtmFormElementSubmitter.submit:a.submit};var qc=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},rc=function(a,b){return a<b?-1:a>b?1:0};var U;a:{var sc=O.navigator;if(sc){var tc=sc.userAgent;if(tc){U=tc;break a}}U=""};var uc=function(){return-1!=U.indexOf("Edge")};var vc=-1!=U.indexOf("Opera")||-1!=U.indexOf("OPR"),W=-1!=U.indexOf("Edge")||-1!=U.indexOf("Trident")||-1!=U.indexOf("MSIE"),wc=-1!=U.indexOf("Gecko")&&!(-1!=U.toLowerCase().indexOf("webkit")&&!uc())&&!(-1!=U.indexOf("Trident")||-1!=U.indexOf("MSIE"))&&!uc(),xc=-1!=U.toLowerCase().indexOf("webkit")&&!uc(),yc=function(){var a=U;if(wc)return/rv\:([^\);]+)(\)|;)/.exec(a);if(W&&uc())return/Edge\/([\d\.]+)/.exec(a);if(W)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(xc)return/WebKit\/(\S+)/.exec(a)},
zc=function(){var a=O.document;return a?a.documentMode:void 0},Ac=function(){if(vc&&O.opera){var a=O.opera.version;return"function"==pa(a)?a():a}var b="",d=yc();d&&(b=d?d[1]:"");if(W&&!uc()){var c=zc();if(c>parseFloat(b))return String(c)}return b}(),Bc={},Cc=function(a){var b;if(!(b=Bc[a])){for(var d=0,c=qc(String(Ac)).split("."),e=qc(String(a)).split("."),f=Math.max(c.length,e.length),g=0;0==d&&g<f;g++){var h=c[g]||"",l=e[g]||"",m=RegExp("(\\d*)(\\D*)","g"),k=RegExp("(\\d*)(\\D*)","g");do{var n=
m.exec(h)||["","",""],r=k.exec(l)||["","",""];if(0==n[0].length&&0==r[0].length)break;d=rc(0==n[1].length?0:parseInt(n[1],10),0==r[1].length?0:parseInt(r[1],10))||rc(0==n[2].length,0==r[2].length)||rc(n[2],r[2])}while(0==d)}b=Bc[a]=0<=d}return b},Dc=O.document,Ec=zc(),Fc=!Dc||!W||!Ec&&uc()?void 0:Ec||("CSS1Compat"==Dc.compatMode?parseInt(Ac,10):5);var Gc;if(!(Gc=!wc&&!W)){var Hc;if(Hc=W)Hc=W&&(uc()||9<=Fc);Gc=Hc}Gc||wc&&Cc("1.9.1");W&&Cc("9");var Ic=function(a){Ic[" "](a);return a};Ic[" "]=function(){};var na=function(a,b){var d="";W&&!Jc(a)&&(d='<script>document.domain="'+document.domain+'";\x3c/script>'+d);var c="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+d+"</head><body>"+b+"</body></html>";if(Kc)a.srcdoc=c;else if(Lc){var e=a.contentWindow.document;e.open("text/html","replace");e.write(c);e.close()}else Mc(a,c)},Kc=xc&&"srcdoc"in document.createElement("iframe"),Lc=wc||xc||W&&Cc(11),Mc=function(a,b){W&&Cc(7)&&!Cc(10)&&6>Nc()&&Oc(b)&&(b=Pc(b));var d=function(){a.contentWindow.goog_content=
b;a.contentWindow.location.replace("javascript:window.goog_content")};W&&!Jc(a)?Qc(a,d):d()},Nc=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},Jc=function(a){try{var b;var d=a.contentWindow;try{var c;if(c=!!d&&null!=d.location.href)b:{try{Ic(d.foo);c=!0;break b}catch(e){}c=!1}b=c}catch(f){b=!1}return b}catch(g){return!1}},Rc=0,Qc=function(a,b){var d="goog_rendering_callback"+Rc++;window[d]=b;a.src="javascript:'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+d+";window.parent."+d+" = null;continuation();})()\x3c/script>'"},Oc=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},Pc=function(a){for(var b=unescape(encodeURIComponent(a)),d=Math.floor(b.length/2),c=[],e=0;e<d;++e)c[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(c[d]=b.charAt(b.length-1));return c.join("")};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */
var _img=function(a,b,d){var c=oa('<a href="'+a["7"]+'"></a>')[0].href,e=a[""];if(e)var f=c.charAt(c.length-1),c=c+((0<=c.indexOf("?")?"?"==f||"&"==f?"":"&":"?")+e+"="+a[""]);p(c,b,d)};_img.a="img";_img.b=["customPixels"];var Wc={},Yc=function(a,b,d,c,e){if(!pb)return!1;var f=Wc[a];f||(f={id:a,B:[],S:0,ma:null,ra:!1},Wc[a]=f);var g={id:a+":"+f.B.length,Ma:d,Ha:c,A:b,ca:0,Z:e||null,qa:0,R:!1};f.B.push(g);null===b?(g.R=!0,d(null)):Xc(f);return!0},Xc=function(a){for(var b=a.S;b<a.B.length;b++){var d=a.B[b],c=b==a.S;if(!d.R&&!Zc(c,d))break;d.R&&c&&a.S++}a.B.length>a.S&&(a.ma||(a.ma=x.setTimeout(function(){a.ma=null;Xc(a)},80)),ka||a.ra||(a.ra=!0,la.push(function(){Xc(a)})))},Zc=function(a,b){var d=[];if(b.A){var c=$c(b.A,
b.id),e=null;b.Z&&(e=$c(b.Z,b.id+"-t"));for(var f=0;f<c.length;f++){var g=c[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!ka&&(null===b.Z.f||b.qa+d.length<b.Z.f)))break;d.push({element:g,lb:h})}}if(!ka&&b.Ha&&(!a||null==b.A.f||b.A.f!=b.ca+d.length))return!1;for(var l=0;l<d.length;l++){var m=d[l].element,k=d[l].lb;b.ca++;ad(m,b.id);k&&(b.qa++,ad(k,b.id+"-t"));b.Ma(m,k)}if(b.A.f&&b.A.f==b.ca||ka)b.R=!0;return!0},ad=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=
!0},$c=function(a,b){for(var d=S(a.j)||[],c=[],e=0;e<d.length;e++){var f=d[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){var g;if(g=a.m){var h;a:{for(var l=f;l;){if(l.nextSibling){h=!0;break a}l=l.parentNode}h=!1}g=!h}if(g)break;c.push(f)}}return c};var nd,od;
var yd=function(a){return function(){}},zd=function(a){return function(){}};var Qd=function(a){var b=x||O,d=b.onerror,c=!1;xc&&!Cc("535.3")&&(c=!c);b.onerror=function(b,f,g,h,l){d&&d(b,f,g,h,l);a({message:b,fileName:f,eb:g,Bb:h,error:l});return c}};var me=43,ne=[],oe=[],Kb=[],pe=new Fa,qe=[],Z=[],gc=[],hc=[],re=function(){this.s=[]};re.prototype.set=function(a,b){this.s.push([a,b]);return this};re.prototype.resolve=function(a,b){for(var d={},c=0;c<this.s.length;c++){var e=se(this.s[c][0],a,b),f=se(this.s[c][1],a,b);d[e]=f}return d};var te=function(a){this.index=a};
te.prototype.resolve=function(a,b){var d=Kb[this.index];if(d&&!b(d)){var c=d["4"];if(a){if(a.get(c))return;a.set(c,!0)}d=se(d,a,b);a&&a.set(c,!1);return Ga(d)}};
var _M=function(a){return new te(a)},ue=function(a){this.resolve=function(b,d){for(var c=[],e=0;e<a.length;e++)c.push(se(ne[a[e]],b,d));return c.join("")}},_T=function(a){return new ue(arguments)},ve=function(a){function b(b){for(var c=1;c<a.length;c++)if(a[c]==b)return!0;return!1}this.resolve=function(d,c){var e=se(a[0],d,c);if(a[0]instanceof
te&&b(8)&&b(16)){var f="gtm"+da++;pe.set(f,e);return'google_tag_manager["GTM-TR24NF"].macro(\''+f+"')"}for(var e=String(e),g=1;g<a.length;g++)e=Y[a[g]](e);return e}},_E=function(a,b){return new ve(arguments)},Nb=function(a,b){return se(a,new Fa,b)},se=function(a,b,d){var c=a;if(a instanceof te||a instanceof re||a instanceof ue||a instanceof ve)return a.resolve(b,d);if(P(a))for(var c=[],e=0;e<a.length;e++)c[e]=se(a[e],b,d);else if(a&&"object"==typeof a){var c={},f;for(f in a)a.hasOwnProperty(f)&&(c[f]=
se(a[f],b,d))}return c},we=function(a,b){var d=b[a],c=d;if(d instanceof te||d instanceof ve||d instanceof ue)c=d;else if(P(d))for(var c=[],e=0;e<d.length;e++)c[e]=we(d[e],b);else if("object"==typeof d){var c=new re,f;for(f in d)d.hasOwnProperty(f)&&c.set(b[f],we(d[f],b))}return c},ye=function(a,b){for(var d=b?b.split(","):[],c=0;c<d.length;c++){var e=d[c]=d[c].split(":");0==a&&(e[1]=ne[e[1]]);if(1==a)for(var f=xe(e[0]),e=d[c]={},g=0;g<f.length;g++){var h=oe[f[g]];e[h[0]]=h[1]}if(2==a)for(g=0;4>g;g++)e[g]=
xe(e[g]);3==a&&(d[c]=ne[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var l=0;l<e[g].length;l++)e[g][l]=ne[e[g][l]]}else e[g]=[];5==a&&(d[c]=e[0])}return d},xe=function(a){var b=[];if(!a)return b;for(var d=0,c=0;c<a.length&&d<me;d+=6,c++){var e=a&&a.charCodeAt(c)||65;if(65!=e){var f=0,f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&f&&b.push(d);2&f&&b.push(d+1);4&f&&b.push(d+2);8&f&&b.push(d+3);16&f&&b.push(d+4);32&f&&b.push(d+5)}}return b},ze=function(a,b,
d){a.push.apply(a,ye(b,d))};var Ae=function(a){var b=this;this.C=this.Da=!1;this.Ea=[];this.xa=[];this.aa={};this.G=function(){b.C||Ja(b.Ea);b.C=!0;T[a]&&(T[a].executed=!0,T[a].succeeded=!0)};this.F=function(){b.C||Ja(b.xa);b.C=!0;T[a]&&(T[a].executed=!0,T[a].succeeded=!1)};this.h=za},Be=function(a,b){a.Ea.push(b)},Ce=function(a,b){a.xa.push(b)},De=function(){this.i=[];this.I=[];this.va={};this.ha=[];this.D=0;this.Ba={};this.Fa={}};De.prototype.addListener=function(a){this.ha.push(a)};
var Ee=function(a,b,d,c,e,f){if(!d.C){a.i[b]=d;void 0==c&&(c=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);P(c)||(c=["or",c]);P(e)||(e=[e]);P(f)||(f=[f]);a.va[b]=c;a.Ba[b]=0<e.length;a.Fa[b]=0<f.length;a.D++;var g=function(){0<a.D&&a.D--;0<a.D||Ja(a.ha)};Be(d,g);Ce(d,g)}},Fe=function(a,b,d){a.i[b]&&(Be(a.i[b],function(){d(b,!0)}),Ce(a.i[b],function(){d(b,!1)}))},Ge=function(a,b){var d=!1;return function(c,e){var f=Ba(a,c);d||0>f||("or"==a[0]?e?(d=!0,b()):(a.splice(f,1),1==a.length&&(d=!0)):e?(a.splice(f,
1),1==a.length&&(d=!0,b())):d=!0)}},Je=function(a,b){var d=[],c=function(a){var b=Z[a],e=void 0===b[""]?[]:b[""],e=P(e)?e:[e];0<e.length&&c(e[0]);d.push(a);var f=void 0===b[""]?[]:b[""],f=P(f)?f:[f];0<f.length&&c(f[0])};c(b);for(var e=0;e<d.length;e++){var f=He(a,b,d[e]);e<d.length-1&&(Be(f,Ie(a,b,d[e+1],d[e])),Ce(f,function(){}))}a.I[d[0]].aa[b]=!0;return d[0]},Ie=function(a,b,d,c){return function(){if(He(a,b,c).aa[b]){var e=
He(a,b,d);e.aa[b]=!0;e.h()}}},He=function(a,b,d){if(!a.I[d]){var c=a.i[d]?a.i[d]:Ke(Z[d]);c.aa[b]=!1;a.I[d]=c}return a.I[d]};var Le=function(a,b){return function(){a["8"]=b.G;a["9"]=b.F;var d=a["6"],c=b.Da,e=!(!T[d]||!T[d].executed),f=!(!T[d]||!T[d].oncePerLoad),g=!(!T[d]||!T[d].oncePerEvent);!c&&!e||!c&&!f||!f&&!g?(b.Da=!0,Ga(a,b.G,b.F)):T[d]&&T[d].succeeded?b.G():b.F()}},Ke=function(a){var b=new Ae(a["6"]);Be(b,yd(a));Ce(b,zd(a));b.h=Le(a,b);return b};var Qe,Re;var Pb=function(){};var df=function(){var a=[];return function(b,d){if(void 0===a[b]){var c=qe[b]&&Nb(qe[b],d);a[b]=[c&&Ga(c),c]}return a[b]}},ef=function(a,b){for(var d=b[0],c=0;c<d.length;c++)if(!a.w(d[c],a.g)[0])return!1;for(var e=b[2],c=0;c<e.length;c++)if(a.w(e[c],a.g)[0])return!1;return!0},ff=!1,Fb=function(a,b,d){switch(a){case "gtm.js":if(ff)return!1;ff=!0;break;case "gtm.sync":if(D("gtm.snippet")!=tb)return!1}D("tagTypeBlacklist");for(var c={name:a,N:b||za,M:xe(),X:xe(),w:df(),g:ob()},e=[],f=0;f<gc.length;f++)if(ef(c,
gc[f])){e[f]=!0;for(var g=c,h=gc[f],l=h[1],m=0;m<l.length;m++)g.M[l[m]]=!0;for(var k=h[3],m=0;m<k.length;m++)g.X[k[m]]=!0}else e[f]=!1;var n=[];for(var r=0;r<me;r++)if(c.M[r]&&!c.X[r])if(c.g(Z[r])){}else{n[r]=Nb(Z[r],c.g);}c.Y=
n;for(var t=new De,B=0;B<me;B++)if(c.M[B]&&!c.X[B]&&!c.g(Z[B])){var u=c.Y[B],A=Ke(u);Ee(t,B,A,u[""],u[""],u[""]);if(u[""])break}t.addListener(c.N);for(var E=[],F=[],w=0;w<t.i.length;w++){var y=t.i[w];if(y){var z=t.va[w],v=t.Ba[w],G=t.Fa[w];if(0!=z.length||v||G){if(0<z.length)for(var V=Ge(z,y.h),Q=0;Q<z.length;Q++)z[Q]!=
w&&Fe(t,z[Q],V);if(v||G){var ta=Je(t,w);F.push(ta)}}else E.push(w)}}for(w=0;w<E.length;w++)t.i[E[w]].h();for(w=0;w<F.length;w++)t.I[F[w]].h();0<t.D||Ja(t.ha);d&&K(d)&&d({passingRules:e,resolvedTags:c.Y});
return 0<c.Y.length};var gf={macro:function(a){if(pe.contains(a))return pe.get(a)}};gf.dataLayer=jb;gf.Qa=function(){var a=x.google_tag_manager;a||(a=x.google_tag_manager={});a["GTM-TR24NF"]||(a["GTM-TR24NF"]=gf)};ne.push.apply(ne,function(){for(var a=[_re,_u,'url',_M(0),'.*',_eq,_e,'_event',_M(1),'gtm.js','',_img,'//','adadvisor.net/adscores/r.pixel?sid\x3d9212270798',_T(12,13),1,'url hostname','host','url path','path',_f,'referrer','event',_v,'element','gtm.element','element classes','gtm.elementClasses','element id','gtm.elementId','element target','gtm.elementTarget',_et,'element text','element url','gtm.elementUrl','history new url fragment','gtm.newUrlFragment','history old url fragment','gtm.oldUrlFragment','history new state','gtm.newHistoryState','history old state','gtm.oldHistoryState','history change source','gtm.historyChangeSource'],b=[],d=0;d<a.length;d++)b[d]=we(d,a);return b}());ze(oe,0,"3:0,3:1,4:2,0:3,1:4,3:5,3:6,4:7,0:8,1:9,3:11,7:14,6:15,4:16,2:17,4:18,2:19,3:20,4:21,4:22,3:23,4:24,5:25,4:26,5:27,4:28,5:29,4:30,5:31,3:32,4:33,4:34,5:35,4:36,5:37,4:38,5:39,4:40,5:41,4:42,5:43,4:44,5:45");ze(Kb,1,"G,AD,CAG,CAY,AAgB,ABAC,AAAc,AAAkB,AAAEG,AAAEY,AAAAgB,AAAEAG,AAAEAY,AAAEAgB,AAAEAAG,AAAEAAY,AAAEAAgB");ze(qe,1,"Z,gM");ze(Z,1,"AwB");ze(gc,2,"D:B::");ze(hc,4,"10:");gf.Qa();
(function(a){})("async");
(function(){var a=I("dataLayer",[],!1),b=I("google_tag_manager",{},!1),b=b["dataLayer"]=b["dataLayer"]||{};la.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Ya.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var d=a.push;a.push=function(){var b=[].slice.call(arguments,0);d.apply(a,b);for(Gb.push.apply(Gb,b);300<this.length;)this.shift();return Qb()};Gb.push.apply(Gb,a.slice(0));q(Qb)})();
if("interactive"==N.readyState&&!N.createEventObject||"complete"==N.readyState)Qa();else{R(N,"DOMContentLoaded",Qa);R(N,"readystatechange",Qa);if(N.createEventObject&&N.documentElement.doScroll){var hf=!0;try{hf=!x.frameElement}catch(jf){}hf&&Sa()}R(x,"load",Qa)}"complete"===N.readyState?$a():R(x,"load",$a);
(function(a){})("async");for(var kf=0;kf<Z.length;kf++){var lf=Z[kf];T[lf["6"]]={oncePerEvent:!!lf[""],oncePerLoad:!!lf[""],executed:!1,succeeded:!1}};var _vs="res_ts:1430781240222000,srv_cl:93238888,ds:live,cv:3";
})()
